/**
 * Master Data Wilayah — Dummy Dataset untuk Cascade Dropdown
 * Master Canvasing • MPM AHASS Canvasing System
 *
 * Struktur bertingkat 4 level:
 *   WILAYAH_INDONESIA[provinsi][kabupaten] = daftar kecamatan
 *
 * Nilai pada level kabupaten dapat berupa:
 *   - OBJECT : { '<KECAMATAN>': ['<KELURAHAN>', ...] }  → kelurahan tersedia
 *   - ARRAY  : ['<KECAMATAN>', ...]                     → kelurahan belum didata
 *
 * Untuk kecamatan tanpa daftar kelurahan, getKelurahanList() memakai fallback
 * berupa nama kecamatan itu sendiri (lihat "Catatan pengembangan" pada
 * docs/master-canvasing.md).
 */

const WILAYAH_INDONESIA = {

  /* ====================================================================
     JAWA TIMUR — 38 Kabupaten/Kota (lengkap)
     ==================================================================== */
  'JAWA TIMUR': {

    /* ---- Area operasional utama: kelurahan lengkap ---- */
    'KAB. SIDOARJO': {
      'BALONGBENDO': ['BAKALAN WRINGINPITU', 'BAKUNG PRINGGODANI', 'BAKUNG TEMENGGUNGAN', 'BOGEM PINGGIR', 'BUDUGSIDOREJO', 'GAGANG KEPUHSARI', 'JABARAN', 'JERUK LEGI', 'KEDUNGSUKODANI', 'KEMANGSEN', 'PENAMBANGAN', 'SEDURI', 'SEKETI', 'SINGKALAN', 'SUMOKEMBANGSRI', 'TAMBAK KEMERAKAN', 'WATESARI', 'WONOKARANG', 'WONOKUPANG'],
      'BUDURAN': ['BANJARKEMANTREN', 'BANJARSARI', 'BUDURAN', 'DAMARSI', 'DUKUH TENGAH', 'ENTALSEWU', 'PAGERWOJO', 'PRASUNG', 'SEBANI', 'SIDOKEPUNG', 'SIDOKERTO', 'SIDOMULYO', 'SIWALANPANJI', 'SUKOREJO', 'WADUNGASIH'],
      'CANDI': ['BALONGDOWO', 'BALONGGABUS', 'BLIGO', 'CANDI', 'DURUNGBANJAR', 'DURUNGBEDUG', 'GELAM', 'JAMBANGAN', 'KALIPECABEAN', 'KARANGTANJUNG', 'KEDUNGKENDO', 'KEDUNGPELUK', 'KENDALPECABEAN', 'KLURAK', 'LARANGAN', 'NGAMPELSARI', 'SEPANDE', 'SIDODADI', 'SUGIHWARAS', 'SUMOKALI', 'SUMORAME', 'TENGGULUNAN', 'WEDORO KLURAK'],
      'GEDANGAN': ['BANGAH', 'GANTING', 'GEDANGAN', 'GEMURUNG', 'KARANGBONG', 'KEBOANANOM', 'KEBOANSIKEP', 'KETAJEN', 'KRAGAN', 'PUNGGUL', 'SAWOTRATAP', 'SEMAMBUNG', 'SRUNI', 'TEBEL', 'WEDI'],
      'JABON': ['BALONGTANI', 'DUKUHSARI', 'JEMIRAHAN', 'KEBOGUYANG', 'KEDUNGCANGKRING', 'KEDUNGPANDAN', 'KEDUNGREJO', 'KUPANG', 'PANGGREH', 'PEJARAKAN', 'PERMISAN', 'SEMAMBUNG', 'TAMBAKKALISOGO', 'TRAJENG'],
      'KREMBUNG': ['BALONGGARUT', 'CANGKRING', 'GADING', 'JENGGOT', 'KANDANGAN', 'KEDUNGRAWAN', 'KEDUNGSUMUR', 'KEPER', 'KERET', 'KREMBUNG', 'LEMUJUT', 'MOJORUNTUT', 'PLOSO', 'REJENI', 'TAMBAKREJO', 'TANJEG WAGIR', 'WALUH', 'WANGKAL', 'WONOMLATI'],
      'KRIAN': ['BARENGKRAJAN', 'GAMPING', 'JATIKALANG', 'JERUK GAMPING', 'JUNWANGI', 'KATERUNGAN', 'KEBOHARAN', 'KEMASAN', 'KERTOSARI', 'KRATON', 'KRIAN', 'PONOKAWAN', 'SEDENGANMIJEN', 'SIDOMOJO', 'SIDOMULYO', 'SIDOREJO', 'TAMPUNG', 'TERIK', 'TERUNGKULON', 'TERUNGWETAN', 'WATUGOLONG'],
      'PORONG': ['CANDIPARI', 'GEDANG', 'GLAGAHARUM', 'JATIREJO', 'JUWETKENONGO', 'KEBAKALAN', 'KEDUNGBOTO', 'KEDUNGSOLO', 'LAJUK', 'MINDI', 'PAMOTAN', 'PESAWAHAN', 'PLUMBON', 'PORONG', 'RENOKENONGO', 'SIRING', 'WUNUT'],
      'PRAMBON': ['BULANG', 'CANGKRINGTURI', 'GAMPANG', 'GEDANGROWO', 'JATIKALANG', 'JEDONGCANGKRING', 'KAJARTENGGULI', 'KEDUNGKEMBAR', 'KEDUNGSUGO', 'KEDUNGWONOKERTO', 'PRAMBON', 'SIMOANGIN-ANGIN', 'SIMPANG', 'TEMU', 'WATUTULIS', 'WIROBITING', 'WONOPLINTAHAN'],
      'SEDATI': ['BANJAR KEMUNING', 'BETRO', 'BUNCITAN', 'CEMANDI', 'GISIK CEMANDI', 'KALANGANYAR', 'KWANGSAN', 'PABEAN', 'PEPE', 'PRANTI', 'PULUNGAN', 'SEDATI AGUNG', 'SEDATI GEDE', 'SEGORO TAMBAK', 'SEMAMPIR', 'TAMBAK CEMANDI'],
      'SIDOARJO': ['BANJARBENDO', 'BLURU KIDUL', 'BULUSIDOKARE', 'CELEP', 'CEMENGBAKALAN', 'CEMENGKALANG', 'GEBANG', 'JATI', 'KEBONSARI', 'KEMIRI', 'LEBO', 'LEMAHPUTRO', 'MAGERSARI', 'PUCANG', 'PUCANGANOM', 'RANGKAHKIDUL', 'SARIROGO', 'SEKARDANGAN', 'SIDOKARE', 'SIDOKLUMPUK', 'SIDOKUMPUL', 'SUKO', 'SUMPUT', 'URANGAGUNG JEDONG'],
      'SUKODONO': ['ANGGASWANGI', 'BANGSRI', 'CANGKRINGSARI', 'JOGOSATRU', 'JUMPUTREJO', 'KEBONAGUNG', 'KLOPOSEPULUH', 'MASANGANKULON', 'MASANGANWETAN', 'NGARESREJO', 'PADEMONEGORO', 'PANJUNAN', 'PEKARUNGAN', 'PLUMBUNGAN', 'SAMBUNGREJO', 'SUKO', 'SUKODONO', 'SURUH', 'WILAYUT'],
      'TAMAN': ['BEBEKAN', 'BOHAR', 'BRINGINBENDO', 'GELURAN', 'GILANG', 'JEMUNDO', 'KALIJATEN', 'KEDUNGTURI', 'KETEGAN', 'KLETEK', 'KRAMATJEGU', 'KREMBANGAN', 'NGELOM', 'PERTAPANMADYA', 'SADANG', 'SAMBIBULU', 'SEPANJANG', 'SIDODADI', 'TAMAN', 'TANJUNGSARI', 'TAWANGSARI', 'TROSOBO', 'WAGE', 'WONOCOLO'],
      'TANGGULANGIN': ['BANJARASRI', 'BANJARPANJI', 'BOTORO', 'GANGGANGPANJANG', 'GEMPOLSARI', 'KALIDAWIR', 'KALIREJO', 'KALISAMPURNO', 'KALITENGAH', 'KEDENSARI', 'KEDUNGBANTENG', 'KEDUNGBENDO', 'KETAPANG', 'KETEGAN', 'NGABAN', 'PENATARSEWU', 'PUTAT', 'RANDEGAN', 'SENTUL'],
      'TARIK': ['BALONGGENDING', 'GAMPINGROWO', 'GEDANGROWO', 'JANTI', 'KALIMATI', 'KEDINDING', 'KEDUNGBOCOK', 'KEMUNING', 'KLANTINGSARI', 'KRAMAT TEMENGGUNG', 'MERGOBENER', 'MERGOSARI', 'MINDUGADING', 'SEBANI', 'SEGODOBANCANG', 'SINGOGALIH', 'TARIK'],
      'TULANGAN': ['GELANG', 'GRABAGAN', 'GRINTING', 'JANTI', 'KAJEKSAN', 'KEBARON', 'KEDONDONG', 'KENONGO', 'KEPADANGAN', 'KEPATIHAN', 'KEPUNTEN', 'MEDALEM', 'MODONG', 'PANGKEMIRI', 'SINGOPADU', 'SUDIMORO', 'TLASIH', 'TULANGAN'],
      'WARU': ['BERBEK', 'BUNGURASIH', 'JANTI', 'KEDUNGREJO', 'KEPUHKIRIMAN', 'KUREKSARI', 'MEDAENG', 'NGINGAS', 'PEPELEGI', 'TAMBAK OSO', 'TAMBAK REJO', 'TAMBAK SAWAH', 'TAMBAK SUMUR', 'WADUNGASRI', 'WARU', 'WEDORO'],
      'WONOAYU': ['BECIRONGENGOR', 'CANDINEGORO', 'JIMBARANKULON', 'JIMBARANWETAN', 'KARANGPURI', 'KETIMANG', 'LAMBANGAN', 'MULYODADI', 'PAGERNGUMBUK', 'PLAOSAN', 'PLOSO', 'POPOH', 'SAWOCANGKRING', 'SEMAMBUNG', 'SIMOANGIN-ANGIN', 'SIMOKETAWANG', 'SUMBEREJO', 'TANGGUL', 'WONOAYU', 'WONOKALANG', 'WONOKASIAN']
    },

    'KOTA SURABAYA': {
      'ASEMROWO': ['ASEMROWO', 'GENTING KALIANAK', 'TAMBAK SARIOSO'],
      'BENOWO': ['KANDANGAN', 'ROMOKALISARI', 'SEMEMI', 'TAMBAK OSO WILANGUN'],
      'BUBUTAN': ['ALUN-ALUN CONTONG', 'BUBUTAN', 'GUNDIH', 'JEPARA', 'TEMBOK DUKUH'],
      'BULAK': ['BULAK', 'KEDUNG COWEK', 'KENJERAN', 'SUKOLILO BARU'],
      'DUKUH PAKIS': ['DUKUH KUPANG', 'DUKUH PAKIS', 'GUNUNGSARI', 'PRADAH KALI KENDAL'],
      'GAYUNGAN': ['DUKUH MENANGGAL', 'GAYUNGAN', 'KETINTANG', 'MENANGGAL'],
      'GENTENG': ['EMBONG KALIASIN', 'GENTENG', 'KAPASARI', 'KETABANG', 'PENELEH'],
      'GUBENG': ['AIRLANGGA', 'BARATA JAYA', 'GUBENG', 'KERTAJAYA', 'MOJO', 'PUCANG SEWU'],
      'GUNUNG ANYAR': ['GUNUNG ANYAR', 'GUNUNG ANYAR TAMBAK', 'RUNGKUT MENANGGAL', 'RUNGKUT TENGAH'],
      'JAMBANGAN': ['JAMBANGAN', 'KARAH', 'KEBONSARI', 'PAGESANGAN'],
      'KARANG PILANG': ['KARANG PILANG', 'KEBRAON', 'KEDURUS', 'WARUGUNUNG'],
      'KENJERAN': ['BULAK BANTENG', 'SIDOTOPO WETAN', 'TAMBAK WEDI', 'TANAH KALI KEDINDING'],
      'KREMBANGAN': ['DUPAK', 'KEMAYORAN', 'KREMBANGAN SELATAN', 'MOROKREMBANGAN', 'PERAK BARAT'],
      'LAKARSANTRI': ['BANGKINGAN', 'JERUK', 'LAKARSANTRI', 'LIDAH KULON', 'LIDAH WETAN', 'SUMUR WELUT'],
      'MULYOREJO': ['DUKUH SUTOREJO', 'KALIJUDAN', 'KALISARI', 'KEJAWAN PUTIH TAMBAK', 'MANYAR SABRANGAN', 'MULYOREJO'],
      'PABEAN CANTIAN': ['BONGKARAN', 'KREMBANGAN UTARA', 'NYAMPLUNGAN', 'PERAK TIMUR', 'PERAK UTARA'],
      'PAKAL': ['BABAT JERAWAT', 'BENOWO', 'PAKAL', 'SUMBER REJO', 'TAMBAK DONO'],
      'RUNGKUT': ['KALI RUNGKUT', 'KEDUNG BARUK', 'MEDOKAN AYU', 'PENJARINGAN SARI', 'RUNGKUT KIDUL', 'WONOREJO'],
      'SAMBIKEREP': ['BERINGIN', 'LONTAR', 'MADE', 'SAMBIKEREP'],
      'SAWAHAN': ['BANYU URIP', 'KUPANG KRAJAN', 'PAKIS', 'PETEMON', 'PUTAT JAYA', 'SAWAHAN'],
      'SEMAMPIR': ['AMPEL', 'PEGIRIAN', 'SIDOTOPO', 'UJUNG', 'WONOKUSUMO'],
      'SIMOKERTO': ['KAPASAN', 'SIDODADI', 'SIMOKERTO', 'SIMOLAWANG', 'TAMBAKREJO'],
      'SUKOLILO': ['GEBANG PUTIH', 'KEPUTIH', 'KLAMPIS NGASEM', 'MENUR PUMPUNGAN', 'NGINDEN JANGKUNGAN', 'SEMOLOWARU'],
      'SUKOMANUNGGAL': ['PUTAT GEDE', 'SIMOMULYO', 'SIMOMULYO BARU', 'SONOKWIJENAN', 'SUKOMANUNGGAL', 'TANJUNGSARI'],
      'TAMBAKSARI': ['DUKUH SETRO', 'GADING', 'KAPAS MADYA BARU', 'PACAR KELING', 'PACAR KEMBANG', 'PLOSO', 'RANGKAH', 'TAMBAKSARI'],
      'TANDES': ['BALONGSARI', 'BANJAR SUGIHAN', 'BUNTARAN', 'GEDANGASIN', 'KARANG POH', 'MANUKAN KULON', 'MANUKAN WETAN', 'TANDES', 'TUBANAN'],
      'TEGALSARI': ['DR. SOETOMO', 'KEDUNGDORO', 'KEPUTRAN', 'TEGALSARI', 'WONOREJO'],
      'TENGGILIS MEJOYO': ['KENDANGSARI', 'KUTISARI', 'PANJANG JIWO', 'TENGGILIS MEJOYO'],
      'WIYUNG': ['BABATAN', 'BALAS KLUMPRIK', 'JAJAR TUNGGAL', 'WIYUNG'],
      'WONOCOLO': ['BENDUL MERISI', 'JEMUR WONOSARI', 'MARGOREJO', 'SIDOSERMO', 'SIWALANKERTO'],
      'WONOKROMO': ['DARMO', 'JAGIR', 'NGAGEL', 'NGAGEL REJO', 'SAWUNGGALING', 'WONOKROMO']
    },

    'KAB. GRESIK': {
      'BALONGPANGGANG': ['BALONGPANGGANG', 'BANJARAGUNG', 'BRINGKANG', 'DAPET', 'KARANGANYAR', 'KEDUNGPRING', 'KLOTOK', 'NGASIN', 'PACUH', 'PUCUNG', 'SEDAPUR KLAGEN', 'WONOREJO'],
      'BENJENG': ['BALONGMOJO', 'BANTER', 'BENJENG', 'BULANGKULON', 'DERMO', 'DELIKSUMBER', 'GLURANPLOSO', 'KALIPADANG', 'KEDUNGSEKAR', 'KEDUNGRUKEM', 'KLAMPOK', 'LUNDO', 'METATU', 'MUNGGUGIANTI', 'SIRNOBOYO'],
      'BUNGAH': ['ABAR-ABIR', 'BEDANTEN', 'BUNGAH', 'GUMENG', 'INDRODELIK', 'KEMANGI', 'MASANGAN', 'MELIRANG', 'MOJOPUROGEDE', 'MOJOPUROWETAN', 'PEGUNDAN', 'RACI KULON', 'RACI TENGAH', 'SIDOKUMPUL', 'SIDOMUKTI', 'SUKOREJO', 'SUKOWATI', 'TANJUNGWIDORO', 'WATUAGUNG'],
      'CERME': ['BANJARSARI', 'BETITING', 'CAGAKAGUNG', 'CERME KIDUL', 'CERME LOR', 'DADAPKUNING', 'DAMPAAN', 'DUNGUS', 'GEDANGKULUT', 'GURANGANYAR', 'IKER-IKER GEGER', 'JONO', 'KAMBINGAN', 'KANDANGAN', 'LENGKONG', 'MOROWUDI', 'NGABETAN', 'NGEMBUNG', 'PADELEGAN', 'SEMAMPIR', 'SUKOANYAR', 'TAMBAKBERAS', 'WEDANI'],
      'DRIYOREJO': ['BAMBE', 'BANJARAN', 'CANGKIR', 'DRIYOREJO', 'GADUNG', 'KESAMBEN WETAN', 'KRIKILAN', 'MOJOSARIREJO', 'MULUNG', 'PETIKEN', 'RANDEGANSARI', 'SUKOREJO', 'SUMPUT', 'TANJUNGAN', 'TENARU', 'WEDORO ANOM'],
      'DUDUKSAMPEYAN': ['AMBENG-AMBENG WATANGREJO', 'BAMBANG', 'DUDUKSAMPEYAN', 'GLANGGANG', 'GREDEK', 'KANDANGAN', 'KAWISTOWINDU', 'KEBONREJO', 'KREMBANGAN', 'PANDANAN', 'PETIS BENEM', 'SAMIRPLAPAN', 'SETRO', 'SUMARI', 'SUMENGKO', 'TAMBAKREJO', 'TIREMENGGAL', 'TUMAPEL', 'WADAK KIDUL', 'WADAK LOR'],
      'DUKUN': ['BABAKSARI', 'BABAKAN', 'BANGERAN', 'DUKUNANYAR', 'IMAAN', 'KARANGCANGKRING', 'MADUMULYOREJO', 'MENTARAS', 'MOJOPETUNG', 'PADANGBANDUNG', 'PETIYIN TUNGGAL', 'SAWO', 'SEMBUNGANYAR', 'SIMBUYUTAN', 'SUKODONO', 'TEBUWUNG', 'TIREMENGGAL', 'WONOKERTO'],
      'GRESIK': ['BEDILAN', 'GAPUROSUKOLILO', 'KARANGPOH', 'KARANGTURI', 'KEBUNGSON', 'KEMUTERAN', 'KRAMATINGGIL', 'KROMAN', 'LUMPUR', 'NGIPIK', 'PEKAUMAN', 'PEKELINGAN', 'PULOPANCIKAN', 'SIDOKUMPUL', 'SIDORUKUN', 'SUKODONO', 'SUKORAME', 'TLOGOBENDUNG', 'TLOGOPATUT', 'TRATE'],
      'KEBOMAS': ['DAHANREJO', 'GENDING', 'GULOMANTUNG', 'INDRO', 'KARANGKERING', 'KAWISANYAR', 'KEBOMAS', 'KEMBANGAN', 'KLANGONAN', 'NGARGOSARI', 'PRAMBANGAN', 'RANDUAGUNG', 'SEGOROMADU', 'SEKARKURUNG', 'SIDOMORO', 'SINGOSARI', 'SUCI', 'TENGGULUNAN'],
      'KEDAMEAN': ['BELAHANREJO', 'CERMENLERANG', 'KATIMOHO', 'KEDAMEAN', 'LAMPAH', 'PLOSO', 'SLEMPIT', 'TANJUNG', 'TULUNG', 'TURIREJO'],
      'MANYAR': ['BANYUWANGI', 'BETOYOGUCI', 'BETOYOKAUMAN', 'GUMENG', 'KARANGREJO', 'LERAN', 'MANYAR SIDOMUKTI', 'MANYAR SIDORUKUN', 'MANYAREJO', 'MOROBAKUNG', 'PEGANDEN', 'PONGANGAN', 'ROOMO', 'SEMBAYAT', 'SUCI', 'SUKOMULYO', 'SUMBERAGUNG', 'TANGGULREJO', 'TEBALO'],
      'MENGANTI': ['BEJI', 'BOBOH', 'BRINGKANG', 'DOMAS', 'DRANCANG', 'GADINGWATU', 'GEMPOLKUREN', 'HENDROSARI', 'HULAAN', 'KEPATIHAN', 'KREMBANGAN', 'LABAN', 'MENGANTI', 'MOJOTENGAH', 'PELEM WATU', 'PRANTI', 'PUTAT LOR', 'RANDUPADANGAN', 'SIDOJANGKUNG', 'SIDOKUMPUL', 'SIDOWUNGU', 'YOSOWILANGUN'],
      'PANCENG': ['BANYUTENGAH', 'CAMPUREJO', 'DALEGAN', 'DOUDO', 'KETANEN', 'PANTENAN', 'PETUNG', 'PRUPUH', 'SIWALAN', 'SUMURBER', 'WOTAN'],
      'SANGKAPURA': ['BALIKTERUS', 'BULULANJANG', 'DAUN', 'DEKATAGUNG', 'GUNUNGTEGUH', 'KEBUNTELUK DALAM', 'KOTAKUSUMA', 'LEBAK', 'PATARSELAMAT', 'PUDAKIT BARAT', 'PUDAKIT TIMUR', 'SAWAHMULYA', 'SIDOGEDUNGBATU', 'SUNGAI TELUK', 'SUNGAIRUJING', 'SUWARI'],
      'SIDAYU': ['ASEMPAPAK', 'BUNDERAN', 'GEDANGAN', 'GOLOKAN', 'KERTOSONO', 'LASEM', 'MOJOASEM', 'MRIYUNAN', 'NGAWENAN', 'PENGULU', 'PURWODADI', 'RANDUBOTO', 'SAMBIPONDOK', 'SIDOMULYO', 'SIDOREJO', 'SRETI', 'SUKOREJO', 'WADENG'],
      'TAMBAK': ['DIPONGGO', 'GELAM', 'GREJEG', 'KEPUHTEGUH', 'KUJUNG', 'PEKALONGAN', 'SUKALELA', 'SUKAOENG', 'TAMBAK', 'TANJUNGORI', 'TELUK JATIDAWANG'],
      'UJUNGPANGKAH': ['BANYUURIP', 'BOLO', 'CANGAAN', 'GLATIK', 'GOSARI', 'KARANGREJO', 'KETAPANGLOR', 'NGIMBOH', 'PANGKAHKULON', 'PANGKAHWETAN', 'SEKAPUK', 'TANJANGAWAN'],
      'WRINGINANOM': ['KEDUNGANYAR', 'KESAMBEN KULON', 'LEBANIWARAS', 'LENGKONG', 'MONDOLUKU', 'PASINAN LEMAHPUTIH', 'PEDAGANGAN', 'SEMBUNG', 'SOOKO', 'SUMBERAME', 'SUMENGKO', 'WATESTANJUNG', 'WRINGINANOM']
    },
    'KAB. JEMBER': {
      'AJUNG': ['AJUNG', 'KLOMPANGAN', 'MANGARAN', 'PANCAKARYA', 'ROWOINDAH', 'SUKAMAKMUR', 'WIROWONGSO'],
      'AMBULU': ['AMBULU', 'ANDONGSARI', 'KARANGANYAR', 'PONTANG', 'SABRANG', 'SUMBEREJO', 'TEGALSARI'],
      'ARJASA': ['ARJASA', 'BITING', 'CANDIJATI', 'DARSONO', 'GAMBIRAN', 'KAMAL', 'KEMUNINGLOR', 'SUKOWIRYO'],
      'BALUNG': ['BALUNGKULON', 'BALUNGLOR', 'BALUNGREJO', 'CURAHLELE', 'GUMELAR', 'KARANGSEMANDING', 'TUTUL'],
      'BANGSALSARI': ['BADEAN', 'BANGSALSARI', 'BANJARSARI', 'GAMBIRAN', 'KARANGSONO', 'LANGKAP', 'PETUNG', 'SUKOREJO', 'TISNOGAMBAR', 'TUGUSARI', 'CURAHKALONG'],
      'GUMUKMAS': ['BAGOREJO', 'GUMUKMAS', 'KARANGANYAR', 'KEPANJEN', 'MENAMPU', 'MOJOMULYO', 'MOJOSARI', 'PURWOASRI'],
      'JELBUK': ['JELBUK', 'PANDUMAN', 'SUCOPANGEPOK', 'SUGER KIDUL', 'SUKOJEMBER', 'SUKOWIRYO'],
      'JENGGAWAH': ['CANGKRING', 'JATIMULYO', 'JATISARI', 'JENGGAWAH', 'KEMUNINGSARI KIDUL', 'SERUT', 'SIDOREJO', 'WONOJATI'],
      'JOMBANG': ['JOMBANG', 'KETING', 'NGAMPELREJO', 'PADOMASAN', 'SARIMULYO', 'WRINGINAGUNG'],
      'KALISAT': ['AJUNG', 'GAMBIRAN', 'GLAGAHWERO', 'GUMUKSARI', 'KALISAT', 'PATEMPURAN', 'PLALANGAN', 'SEBANEN', 'SEDONG', 'SUKORENO', 'SUMBERJERUK', 'SUMBERKALONG'],
      'KALIWATES': ['JEMBER KIDUL', 'KALIWATES', 'KEBON AGUNG', 'KEPATIHAN', 'MANGLI', 'SEMPUSARI', 'TEGAL BESAR'],
      'KENCONG': ['CAKRU', 'KENCONG', 'KRATON', 'PACIRAN', 'WONOREJO'],
      'LEDOKOMBO': ['KARANGPAITON', 'LEMBENGAN', 'SLATENG', 'SUCOLOR', 'SUKOGIDRI', 'SUMBER BULUS', 'SUMBER LESUNG', 'SUMBERANGET', 'LEDOKOMBO', 'SUMBER SALAK'],
      'MAYANG': ['MAYANG', 'MRAWAN', 'SEPUTIH', 'SIDOMUKTI', 'SUMBERKEJAYAN', 'TEGALREJO', 'TEGALWARU'],
      'MUMBULSARI': ['KAWANGREJO', 'LAMPEJI', 'KARANGKEDAWUNG', 'MUMBULSARI', 'SUCO PANGEPOK', 'SUCO', 'TAMANSARI'],
      'PAKUSARI': ['BEDADUNG', 'JATIAN', 'KERTOSARI', 'PAKUSARI', 'PATEMON', 'SUBO', 'SUMBERPINANG'],
      'PANTI': ['GLAGAHWERO', 'KEMIRI', 'PAKIS', 'PANTI', 'SERUT', 'SUCI'],
      'PATRANG': ['BANJAR SENGON', 'BARATAN', 'BINTORO', 'GEBANG', 'JEMBER LOR', 'JUMERTO', 'SLAWU'],
      'PUGER': ['BAGON', 'GRENDEN', 'JAMBEARUM', 'KASIYAN', 'MLOKOREJO', 'MOJOMULYO', 'MOJOSARI', 'PUGER KULON', 'PUGER WETAN', 'WONOSARI', 'WRINGINTELU'],
      'RAMBIPUJI': ['GUGUT', 'KALIWINING', 'NOGOSARI', 'PECORO', 'RAMBIGUNDAM', 'RAMBIPUJI', 'ROWOTAMTU', 'RANDUAGUNG'],
      'SEMBORO': ['PONDOKDALEM', 'PONDOKJOYO', 'REJOAGUNG', 'SEMBORO', 'SIDOMEKAR', 'SIDOMULYO'],
      'SILO': ['GARAHAN', 'HARJOMULYO', 'KARANGHARJO', 'MULYOREJO', 'PACE', 'SEMPOLAN', 'SIDOMULYO', 'SILO', 'SUMBERJATI'],
      'SUKORAMBI': ['DUKUH MENCEK', 'JUBUNG', 'KARANGPRING', 'KLUNGKUNG', 'SUKORAMBI'],
      'SUKOWONO': ['ARJASA', 'BALETBARU', 'DAWUHAN MANGLI', 'MOJOGEMI', 'POJOK', 'SUKOKERTO', 'SUKOSARI', 'SUKOWONO', 'SUMBERDANTI', 'SUMBERWARINGIN'],
      'SUMBERBARU': ['GELANG', 'JAMBESARI', 'JATIROTO', 'KARANGBAYAT', 'PRINGGONDANI', 'REGOSO', 'ROWOTENGAH', 'SUMBERAGUNG', 'YOSORATI'],
      'SUMBERJAMBE': ['CUMEDAK', 'GUNUNG MALANG', 'JAMBEARUM', 'PLERET', 'PRINGGONDANI', 'ROWOSARI', 'SUMBERJAMBE', 'SAPTOSARI', 'RANDUAGUNG'],
      'SUMBERSARI': ['ANTIROGO', 'KARANGREJO', 'KEBONSARI', 'SUMBERSARI', 'TEGAL GEDE', 'WIROLEGI'],
      'TANGGUL': ['DARUNGAN', 'KLATAKAN', 'MANGGISAN', 'PATEMON', 'SELODAKON', 'TANGGUL KULON', 'TANGGUL WETAN', 'KRAMAT SUKOHARJO'],
      'TEMPUREJO': ['ANDONGREJO', 'CURAHNONGKO', 'CURAHTAKIR', 'PONDOKREJO', 'SANEN REJO', 'SIDODADI', 'TEMPUREJO', 'WONOASRI'],
      'UMBULSARI': ['GADINGREJO', 'GUNUNGSARI', 'MUNDUREJO', 'PALERAN', 'SIDOREJO', 'TANJUNGSARI', 'UMBULREJO', 'UMBULSARI', 'TEGALSARI', 'PONDOKJOYO'],
      'WULUHAN': ['AMPEL', 'DUKUHDEMPOK', 'GLUNDENGAN', 'KESILIR', 'LOJEJER', 'TAMANSARI']
    },
    'KAB. MOJOKERTO': {
      'BANGSAL': ['BANGSAL', 'GEMEKAN', 'KEDUNGKWALI', 'KUTOPORONG', 'MOJOTAMPING', 'NGASTEMI', 'PACING', 'PEKUKUHAN', 'PUCUK', 'SADARTENGAH', 'SALEN', 'SIDOMULYO', 'SUMBERTEBU'],
      'DAWARBLANDONG': ['BANYULEGI', 'BRAYUBLANDONG', 'DAWARBLANDONG', 'GUNUNGAN', 'JATIROWO', 'MADURETNO', 'MOROWUDI', 'PULOREJO', 'RANDEGAN', 'SIMONGAGROK', 'TEMUIRENG', 'TEMUWULAN'],
      'DLANGGU': ['BATURONO', 'BEGAGANLIMO', 'DLANGGU', 'JRAMBE', 'KALEN', 'KEDUNGGEDE', 'KEDUNGLENGKONG', 'NGEMBEH', 'PUNGGING', 'SEGUNUNG', 'SUMBERKARANG', 'TALOK', 'TAMPINGMOJO'],
      'GEDEG': ['BATANKRAJAN', 'BERATKULON', 'BERATWETAN', 'GEDEG', 'GEMBONGAN', 'JAPAN', 'JERUKSEGER', 'KEMANTREN', 'LAKARDOWO', 'PAGERJO', 'SIDOHARJO', 'TERUSAN'],
      'GONDANG': ['BEGAGANLIMO', 'BENDUNGANJATI', 'CENTONG', 'DILEM', 'GONDANG', 'JATIDUKUH', 'KALIKATIR', 'KARANGKUTEN', 'KEMASANTANI', 'NGEMBAT', 'PADI', 'POHJEJER', 'PUGERAN', 'TAWAR'],
      'JATIREJO': ['BALEREJO', 'DINOYO', 'GEDANGAN', 'GEBANGSARI', 'JATIREJO', 'KARANGJERUK', 'KUMITIR', 'LEBAKJABUNG', 'MOJOREJO', 'PADUSAN', 'RENDE', 'SUKODONO', 'SUMBERAGUNG', 'TAWANGREJO'],
      'JETIS': ['BANJARSARI', 'BENDUNG', 'CANGGU', 'JAPANAN', 'JETIS', 'KUPANG', 'LAKARDOWO', 'MLIRIP', 'MOJOREJO', 'PARENGAN', 'PERNING', 'SIDOREJO'],
      'KEMLAGI': ['BETRO', 'JAPANAN', 'KEDUNGSARI', 'KEMLAGI', 'KRADENAN', 'MOJODOWO', 'MOJOJAJAR', 'MOJOWATESREJO', 'PANDANKRAJAN', 'PASINAN', 'PURWOJATI', 'SIDOMULYO', 'TERUSAN'],
      'KUTOREJO': ['GEDANGAN', 'KALIGORO', 'KEPUHANYAR', 'KLINTEREJO', 'KUTOREJO', 'MOJOREJO', 'PESANGGRAHAN', 'SAWO', 'SUKOREJO', 'WINDUREJO'],
      'MOJOANYAR': ['GAYAMAN', 'GEBANGMALANG', 'JABON', 'KEPUHANYAR', 'LENGKONG', 'MODONGAN', 'MOJOANYAR', 'NGARJO', 'SADI', 'SUMBERJATI', 'WUNUT'],
      'MOJOSARI': ['AWANG-AWANG', 'BELAHANTENGAH', 'JOTANGAN', 'KAUMAN', 'KEBONDALEM', 'LEMINGGIR', 'MODOPURO', 'MOJOSARI', 'NGRAME', 'PEKUKUHAN', 'PESANGGRAHAN', 'RANDUBANGO', 'SAMBIROTO', 'SEDURI', 'WUNUT'],
      'NGORO': ['BADANG', 'BANDARASRI', 'CANDIHARJO', 'JASEM', 'KESEMEN', 'KUNJOROWESI', 'LOLAWANG', 'MANDUROMANGGUNGGAJAH', 'NGORO', 'SEDATI', 'SUKOREJO', 'TANJUNGKENONGO', 'WATESNEGORO'],
      'PACET': ['BENDUNGANJATI', 'CANDIWATU', 'CEMBOR', 'CEPOKOLIMO', 'CLAKET', 'KEMBANGBELOR', 'KESIMANTENGAH', 'KUTO', 'NOGOSARI', 'PACET', 'PADUSAN', 'PANDANARUM', 'PETAK', 'SAJEN', 'SUMBERKEMBAR', 'TANJUNGKENONGO', 'WARUGUNUNG', 'WIYU'],
      'PUNGGING': ['BALONGMASIN', 'BANGUN', 'BANJARTANGGUL', 'BULULAWANG', 'JABON', 'KEMBANGRINGGIT', 'LEBAKSONO', 'NGEMBEH', 'PLERET', 'PUNGGING', 'PURWOREJO', 'RANDEGAN', 'SEKARGADUNG', 'TAMBAKAGUNG', 'TANGUNAN', 'WATUKENONGO'],
      'PURI': ['BALONGMOJO', 'BANJARAGUNG', 'BANJARSARI', 'KARANGJERUK', 'KEBONAGUNG', 'KENANTEN', 'KETEMASDUNGUS', 'MEDALI', 'MLATEN', 'PURI', 'SUMBERGIRANG', 'SUMOLAWANG', 'TAMBAKAGUNG', 'TUNGGALPAGER'],
      'SOOKO': ['BLIMBINGSARI', 'BRANGKAL', 'JAPAN', 'KARANGKEDAWANG', 'KEDUNGMALING', 'KLINTEREJO', 'MODONGAN', 'NGINGASREMBUNG', 'PUNGGUL', 'SAMBIROTO', 'SOOKO', 'TEMPURAN', 'WRINGINREJO'],
      'TRAWAS': ['BELIK', 'JATIJEJER', 'KEDUNGUDI', 'KETAPANRAME', 'PENANGGUNGAN', 'SELOLIMAN', 'SUKOSARI', 'TAMIAJENG', 'TRAWAS'],
      'TROWULAN': ['BALONGWONO', 'BEJIJONG', 'DOMAS', 'JAMBUWOK', 'JATIPASAR', 'KEJAGAN', 'KEMASAN', 'PANGGIH', 'PAKIS', 'SENTONOREJO', 'TAWANGSARI', 'TEMON', 'TROWULAN', 'WATESUMPAK']
    },

    'KAB. PASURUAN': {
      'BANGIL': ['BENDOMUNGAL', 'DERMO', 'GEMPENG', 'KALIANYAR', 'KALIREJO', 'KAUMAN', 'KERSIKAN', 'KOLURSARI', 'LATEK', 'MANARUWI', 'MASANGAN', 'PATEBON', 'POGAR', 'RACI', 'TAMBAKAN'],
      'BEJI': ['BEJI', 'CANGKRINGMALANG', 'GAJAHBENDO', 'GLANGGANG', 'GUNUNGGANGSIR', 'KEDUNGBOTO', 'KEDUNGRINGIN', 'KENEP', 'PAGAK', 'SIDOWAYAH', 'WONOKOYO', 'WONOSARI'],
      'GEMPOL': ['BULUSARI', 'CARAT', 'GEMPOL', 'JERUKPURUT', 'KEJAPANAN', 'KEPULUNGAN', 'LEGOK', 'NGERONG', 'RANDUPITU', 'SUMBERSUKO', 'WATUKOSEK', 'WONOSARI', 'WONOSUNYO'],
      'GONDANGWETAN': ['BAJANGAN', 'BAYEMAN', 'BROMBONG', 'GAYAM', 'GONDANGREJO', 'GONDANGWETAN', 'KALIREJO', 'KEBONCANDI', 'KEBOIRENG', 'PEKORO', 'PUCANGSARI', 'RANGGEH', 'SEKARPUTIH', 'TENGGILISREJO', 'WONOJATI', 'WONOSARI'],
      'GRATI': ['CUKURGONDANG', 'GRATI TUNON', 'KALIPANG', 'KAMBINGAN REJO', 'KEBONREJO', 'KEDAWUNG', 'PLOSOREJO', 'RANUKLINDUNGAN', 'SUMBERDAWESARI', 'SUMBERAGUNG', 'SUMURWARU', 'TREWUNG'],
      'KEJAYAN': ['AMBAL-AMBIL', 'BENERWOJO', 'COBAN JOYO', 'KEJAYAN', 'KETAWANG', 'KURUNG', 'LAMBANG KUNING', 'LINGGO', 'ORO-ORO PULE', 'PATEBON', 'PUCANGSARI', 'RANDUPITU', 'SLADI', 'SUMBERBANTENG', 'TANGGULANGIN', 'TUNDOSORO', 'WALES', 'WRINGINSARI'],
      'KRATON': ['ASEMKANDANG', 'BENDUNGAN', 'BRINGIN', 'CURAHDUKUH', 'DHOMPO', 'JERUK', 'KALIREJO', 'KEBOTOHAN', 'KRATON', 'MULYOREJO', 'NGABAR', 'PLINGGISAN', 'PUKUL', 'REJOSO', 'SELOTAMBAK', 'TAMBAKREJO', 'TAMBAKSARI', 'WARUNGDOWO'],
      'LEKOK': ['ALASTLOGO', 'BALUNGANYAR', 'BRANANG', 'GEJUGJATI', 'JATIREJO', 'PASINAN', 'SEMEDUSARI', 'SUMBERANYAR', 'TAMPUNG', 'WATES'],
      'LUMBANG': ['BANJARIMBO', 'BULUKANDANG', 'CUKURGUYUNG', 'KARANGASEM', 'KAWEDUSAN', 'LUMBANG', 'WATULUMBUNG', 'WELULANG'],
      'NGULING': ['KAPASAN', 'KEDAWANG', 'KEDUNGBOTO', 'MLATEN', 'NGULING', 'PENUNGGUL', 'SEBALONG', 'SUDIMULYO', 'WATESTANI'],
      'PANDAAN': ['BANJARKEJEN', 'BANJARSARI', 'DURENSEWU', 'JOGOSARI', 'KARANGJATI', 'KEBONWARIS', 'KEMIRISEWU', 'KUTOREJO', 'NOGOSARI', 'PANDAAN', 'PETUNGASRI', 'PLINTAHAN', 'SEBANI', 'SUMBEREJO', 'SUMBERGEDANG', 'TAWANGREJO', 'TUNGGULWULUNG', 'WEDORO'],
      'PASREPAN': ['AMPELSARI', 'GALIH', 'JOGOREPUH', 'KLAKAH', 'LEMAHBANG', 'MANGGUAN', 'PASREPAN', 'PATUGURAN', 'POHGADING', 'SAPULANTE', 'TEMPURAN', 'TEMPURREJO'],
      'POHJENTREK': ['KARANGPANDAN', 'PARERJO', 'PLERET', 'SUKOREJO', 'SUSUKANREJO', 'TIDU', 'WARUNGDOWO'],
      'PRIGEN': ['BULUKANDANG', 'CANDIWATES', 'DAYUREJO', 'JATIARJO', 'KETANIRENG', 'LEDUG', 'LUMBANGREJO', 'PECALUKAN', 'PRIGEN', 'SUKOLILO', 'WATUAGUNG'],
      'PURWODADI': ['CAPANG', 'CENDONO', 'DAWUHAN SENGON', 'GADING', 'GERBO', 'JATISARI', 'LEBAKREJO', 'PARERJO', 'PUCANGSARI', 'PURWODADI', 'SEMUT', 'SENTUL', 'TAMBAKSARI'],
      'PURWOSARI': ['BAKALAN', 'KARANGREJO', 'MARTOPURO', 'PAGAK', 'PUCANGSARI', 'PURWOSARI', 'SEKARMOJO', 'SENGONAGUNG', 'SUKODERMO', 'SUMBERREJO', 'TEJOWANGI'],
      'PUSPO': ['JIMBARAN', 'KELOPOSAWIT', 'PALANGSARI', 'PUSPO', 'PUSUNGMALANG'],
      'REJOSO': ['ARJOSARI', 'JARANGAN', 'KAWISREJO', 'KEDUNGBAKO', 'KEMANTRENREJO', 'KETEGAN', 'KLADEREJO', 'MANIKREJO', 'PANDANREJO', 'REJOSO KIDUL', 'REJOSO LOR', 'SADENGREJO', 'SAMBIREJO', 'SEGOROPURO'],
      'REMBANG': ['ORO-ORO OMBO KULON', 'ORO-ORO OMBO WETAN', 'PANDEAN', 'PEKOREN', 'PEJANGKUNGAN', 'REMBANG', 'TAMPUNG', 'GENENGWARU', 'KALISAT', 'KANIGORO', 'MOJOPARON'],
      'SUKOREJO': ['CANDIBINANGUN', 'GLAGAHSARI', 'GUNTING', 'KALIREJO', 'LECAH', 'NGADIMULYO', 'SUKOREJO', 'SUWAYUWO', 'TANJUNGARUM', 'WONOKERTO'],
      'TOSARI': ['BARUKLINTING', 'KANDANGAN', 'NGADIWONO', 'PODOKOYO', 'SEDAENG', 'TOSARI', 'WONOKITRI'],
      'TUTUR': ['ANDONOSARI', 'BLARANG', 'GENDRO', 'GUNUNGSARI', 'KALIPUCANG', 'KAYUKEBEK', 'PUNGGING', 'SUMBEREJO', 'TLOGOSARI', 'TUTUR', 'WONOSARI'],
      'WINONGAN': ['BANDARAN', 'KARANGTENGAH', 'KEDUNGREJO', 'LEMAHBANG', 'MENDALAN', 'PRODO', 'SRUWI', 'UMBULAN', 'WINONGAN KIDUL', 'WINONGAN LOR'],
      'WONOREJO': ['COBAN BLIMBING', 'JATIGUNTING', 'KARANGJATI', 'KENDANGDUKUH', 'LEBAKREJO', 'SAMBISIRAH', 'WONOREJO']
    },
    /* ---- Sisa Jawa Timur: kecamatan lengkap, kelurahan belum didata ---- */
    'KAB. BANGKALAN': ['AROSBAYA', 'BANGKALAN', 'BLEGA', 'BURNEH', 'GALIS', 'GEGER', 'KAMAL', 'KLAMPIS', 'KOKOP', 'KONANG', 'KWANYAR', 'LABANG', 'MODUNG', 'SEPULU', 'SOCAH', 'TANAH MERAH', 'TANJUNG BUMI', 'TRAGAH'],
    'KAB. BANYUWANGI': ['BANGOREJO', 'BANYUWANGI', 'BLIMBINGSARI', 'CLURING', 'GAMBIRAN', 'GENTENG', 'GIRI', 'GLAGAH', 'GLENMORE', 'KABAT', 'KALIBARU', 'KALIPURO', 'LICIN', 'MUNCAR', 'PESANGGARAN', 'PURWOHARJO', 'ROGOJAMPI', 'SEMPU', 'SILIRAGUNG', 'SINGOJURUH', 'SONGGON', 'SRONO', 'TEGALDLIMO', 'TEGALSARI', 'WONGSOREJO'],
    'KAB. BLITAR': ['BAKUNG', 'BINANGUN', 'DOKO', 'GANDUSARI', 'GARUM', 'KADEMANGAN', 'KANIGORO', 'KESAMBEN', 'NGLEGOK', 'PANGGUNGREJO', 'PONGGOK', 'SANANKULON', 'SELOPURO', 'SELOREJO', 'SRENGAT', 'SUTOJAYAN', 'TALUN', 'UDANAWU', 'WATES', 'WLINGI', 'WONODADI', 'WONOTIRTO'],
    'KAB. BOJONEGORO': ['BALEN', 'BAURENO', 'BOJONEGORO', 'BUBULAN', 'DANDER', 'GAYAM', 'GONDANG', 'KALITIDU', 'KANOR', 'KAPAS', 'KASIMAN', 'KEDEWAN', 'KEDUNGADEM', 'KEPOHBARU', 'MALO', 'MARGOMULYO', 'NGAMBON', 'NGASEM', 'NGRAHO', 'PADANGAN', 'PURWOSARI', 'SEKAR', 'SUGIHWARAS', 'SUKOSEWU', 'SUMBERREJO', 'TAMBAKREJO', 'TEMAYANG', 'TRUCUK'],
    'KAB. BONDOWOSO': ['BINAKAL', 'BONDOWOSO', 'BOTOLINGGO', 'CERMEE', 'CURAHDAMI', 'GRUJUGAN', 'JAMBESARI DARUS SHOLAH', 'KLABANG', 'MAESAN', 'PAKEM', 'PRAJEKAN', 'PUJER', 'SEMPOL', 'SUKOSARI', 'SUMBER WRINGIN', 'TAMAN KROCOK', 'TAMANAN', 'TAPEN', 'TEGALAMPEL', 'TENGGARANG', 'TLOGOSARI', 'WONOSARI', 'WRINGIN'],
    'KAB. JOMBANG': ['BANDAR KEDUNGMULYO', 'BARENG', 'DIWEK', 'GUDO', 'JOGOROTO', 'JOMBANG', 'KABUH', 'KESAMBEN', 'KUDU', 'MEGALUH', 'MOJOAGUNG', 'MOJOWARNO', 'NGORO', 'NGUSIKAN', 'PERAK', 'PETERONGAN', 'PLANDAAN', 'PLOSO', 'SUMOBITO', 'TEMBELANG', 'WONOSALAM'],
    'KAB. KEDIRI': ['BADAS', 'BANYAKAN', 'GAMPENGREJO', 'GROGOL', 'GURAH', 'KANDANGAN', 'KANDAT', 'KAYEN KIDUL', 'KEPUNG', 'KRAS', 'KUNJANG', 'MOJO', 'NGADILUWIH', 'NGANCAR', 'NGASEM', 'PAGU', 'PAPAR', 'PARE', 'PLEMAHAN', 'PLOSOKLATEN', 'PUNCU', 'PURWOASRI', 'RINGINREJO', 'SEMEN', 'TAROKAN', 'WATES'],
    'KAB. LAMONGAN': ['BABAT', 'BLULUK', 'BRONDONG', 'DEKET', 'GLAGAH', 'KALITENGAH', 'KARANGBINANGUN', 'KARANGGENENG', 'KEDUNGPRING', 'KEMBANGBAHU', 'LAMONGAN', 'LAREN', 'MADURAN', 'MANTUP', 'MODO', 'NGIMBANG', 'PACIRAN', 'PUCUK', 'SAMBENG', 'SARIREJO', 'SEKARAN', 'SOLOKURO', 'SUGIO', 'SUKODADI', 'SUKORAME', 'TIKUNG', 'TURI'],
    'KAB. LUMAJANG': ['CANDIPURO', 'GUCIALIT', 'JATIROTO', 'KEDUNGJAJANG', 'KLAKAH', 'KUNIR', 'LUMAJANG', 'PADANG', 'PASIRIAN', 'PASRUJAMBE', 'PRONOJIWO', 'RANDUAGUNG', 'RANUYOSO', 'ROWOKANGKUNG', 'SENDURO', 'SUKODONO', 'SUMBERSUKO', 'TEKUNG', 'TEMPEH', 'TEMPURSARI', 'YOSOWILANGUN'],
    'KAB. MADIUN': ['BALEREJO', 'DAGANGAN', 'DOLOPO', 'GEGER', 'GEMARANG', 'JIWAN', 'KARE', 'KEBONSARI', 'MADIUN', 'MEJAYAN', 'PILANGKENCENG', 'SARADAN', 'SAWAHAN', 'WONOASRI', 'WUNGU'],
    'KAB. MAGETAN': ['BARAT', 'BENDO', 'KARANGREJO', 'KARAS', 'KAWEDANAN', 'KENDAL', 'LEMBEYAN', 'MAGETAN', 'MAOSPATI', 'NGARIBOYO', 'NGUNTORONADI', 'PANEKAN', 'PARANG', 'PLAOSAN', 'PONCOL', 'SIDOREJO', 'SUKOMORO', 'TAKERAN'],
    'KAB. MALANG': ['AMPELGADING', 'BANTUR', 'BULULAWANG', 'DAMPIT', 'DAU', 'DONOMULYO', 'GEDANGAN', 'GONDANGLEGI', 'JABUNG', 'KALIPARE', 'KARANGPLOSO', 'KASEMBON', 'KEPANJEN', 'KROMENGAN', 'LAWANG', 'NGAJUM', 'NGANTANG', 'PAGAK', 'PAGELARAN', 'PAKIS', 'PAKISAJI', 'PONCOKUSUMO', 'PUJON', 'SINGOSARI', 'SUMBERMANJING WETAN', 'SUMBERPUCUNG', 'TAJINAN', 'TIRTOYUDO', 'TUMPANG', 'TUREN', 'WAGIR', 'WAJAK', 'WONOSARI'],
    'KAB. NGANJUK': ['BAGOR', 'BARON', 'BERBEK', 'GONDANG', 'JATIKALEN', 'KERTOSONO', 'LENGKONG', 'LOCERET', 'NGANJUK', 'NGETOS', 'NGLUYU', 'NGRONGGOT', 'PACE', 'PATIANROWO', 'PRAMBON', 'REJOSO', 'SAWAHAN', 'SUKOMORO', 'TANJUNGANOM', 'WILANGAN'],
    'KAB. NGAWI': ['BRINGIN', 'GENENG', 'GERIH', 'JOGOROGO', 'KARANGANYAR', 'KARANGJATI', 'KASREMAN', 'KEDUNGGALAR', 'KENDAL', 'KWADUNGAN', 'MANTINGAN', 'NGAWI', 'NGRAMBE', 'PADAS', 'PANGKUR', 'PARON', 'PITU', 'SINE', 'WIDODAREN'],
    'KAB. PACITAN': ['ARJOSARI', 'BANDAR', 'DONOROJO', 'KEBONAGUNG', 'NAWANGAN', 'NGADIROJO', 'PACITAN', 'PRINGKUKU', 'PUNUNG', 'SUDIMORO', 'TEGALOMBO', 'TULAKAN'],
    'KAB. PAMEKASAN': ['BATUMARMAR', 'GALIS', 'KADUR', 'LARANGAN', 'PADEMAWU', 'PAKONG', 'PALENGAAN', 'PAMEKASAN', 'PASEAN', 'PEGANTENAN', 'PROPPO', 'TLANAKAN', 'WARU'],
    'KAB. PONOROGO': ['BABADAN', 'BADEGAN', 'BALONG', 'BUNGKAL', 'JAMBON', 'JENANGAN', 'JETIS', 'KAUMAN', 'MLARAK', 'NGEBEL', 'NGRAYUN', 'PONOROGO', 'PUDAK', 'PULUNG', 'SAMBIT', 'SAMPUNG', 'SAWOO', 'SIMAN', 'SLAHUNG', 'SOOKO', 'SUKOREJO'],
    'KAB. PROBOLINGGO': ['BANTARAN', 'BANYUANYAR', 'BESUK', 'DRINGU', 'GADING', 'GENDING', 'KOTAANYAR', 'KRAKSAAN', 'KREJENGAN', 'KRUCIL', 'KURIPAN', 'LECES', 'LUMBANG', 'MARON', 'PAITON', 'PAJARAKAN', 'PAKUNIRAN', 'SUKAPURA', 'SUMBER', 'SUMBERASIH', 'TEGALSIWALAN', 'TIRIS', 'TONGAS', 'WONOMERTO'],
    'KAB. SAMPANG': ['BANYUATES', 'CAMPLONG', 'JRENGIK', 'KARANG PENANG', 'KEDUNGDUNG', 'KETAPANG', 'OMBEN', 'PANGARENGAN', 'ROBATAL', 'SAMPANG', 'SOKOBANAH', 'SRESEH', 'TAMBELANGAN', 'TORJUN'],
    'KAB. SITUBONDO': ['ARJASA', 'ASEMBAGUS', 'BANYUGLUGUR', 'BANYUPUTIH', 'BESUKI', 'BUNGATAN', 'JANGKAR', 'JATIBANTENG', 'KAPONGAN', 'KENDIT', 'MANGARAN', 'MLANDINGAN', 'PANARUKAN', 'PANJI', 'SITUBONDO', 'SUBOH', 'SUMBERMALANG'],
    'KAB. SUMENEP': ['AMBUNTEN', 'ARJASA', 'BATANG-BATANG', 'BATUAN', 'BATUPUTIH', 'BLUTO', 'DASUK', 'DUNGKEK', 'GANDING', 'GAPURA', 'GAYAM', 'GILIGENTING', 'GULUK-GULUK', 'KALIANGET', 'KANGAYAN', 'KOTA SUMENEP', 'LENTENG', 'MANDING', 'MASALEMBU', 'NONGGUNONG', 'PASONGSONGAN', 'PRAGAAN', 'RAAS', 'RUBARU', 'SAPEKEN', 'SARONGGI', 'TALANGO'],
    'KAB. TRENGGALEK': ['BENDUNGAN', 'DONGKO', 'DURENAN', 'GANDUSARI', 'KAMPAK', 'KARANGAN', 'MUNJUNGAN', 'PANGGUL', 'POGALAN', 'PULE', 'SURUH', 'TRENGGALEK', 'TUGU', 'WATULIMO'],
    'KAB. TUBAN': ['BANCAR', 'BANGILAN', 'GRABAGAN', 'JATIROGO', 'JENU', 'KENDURUAN', 'KEREK', 'MERAKURAK', 'MONTONG', 'PALANG', 'PARENGAN', 'PLUMPANG', 'RENGEL', 'SEMANDING', 'SENORI', 'SINGGAHAN', 'SOKO', 'TAMBAKBOYO', 'TUBAN', 'WIDANG'],
    'KAB. TULUNGAGUNG': ['BANDUNG', 'BESUKI', 'BOYOLANGU', 'CAMPURDARAT', 'GONDANG', 'KALIDAWIR', 'KARANGREJO', 'KAUMAN', 'KEDUNGWARU', 'NGANTRU', 'NGUNUT', 'PAGERWOJO', 'PAKEL', 'PUCANGLABAN', 'REJOTANGAN', 'SENDANG', 'SUMBERGEMPOL', 'TANGGUNGGUNUNG', 'TULUNGAGUNG'],
    'KOTA BATU': ['BATU', 'BUMIAJI', 'JUNREJO'],
    'KOTA BLITAR': ['KEPANJENKIDUL', 'SANANWETAN', 'SUKOREJO'],
    'KOTA KEDIRI': ['KOTA', 'MOJOROTO', 'PESANTREN'],
    'KOTA MADIUN': ['KARTOHARJO', 'MANGUHARJO', 'TAMAN'],
    'KOTA MALANG': ['BLIMBING', 'KEDUNGKANDANG', 'KLOJEN', 'LOWOKWARU', 'SUKUN'],
    'KOTA MOJOKERTO': ['KRANGGAN', 'MAGERSARI', 'PRAJURIT KULON'],
    'KOTA PASURUAN': ['BUGUL KIDUL', 'GADINGREJO', 'PANGGUNGREJO', 'PURWOREJO'],
    'KOTA PROBOLINGGO': ['KADEMANGAN', 'KANIGARAN', 'KEDOPOK', 'MAYANGAN', 'WONOASIH']
  },
  /* ====================================================================
     JAWA TENGAH — 35 Kabupaten/Kota (lengkap)
     Kelurahan didata untuk kota utama; kabupaten kecamatan saja.
     ==================================================================== */
  'JAWA TENGAH': {
    'KOTA SEMARANG': {
      'BANYUMANIK': ['BANYUMANIK', 'GEDAWANG', 'JABUNGAN', 'NGESREP', 'PADANGSARI', 'PEDALANGAN', 'PUDAKPAYUNG', 'SRONDOL KULON', 'SRONDOL WETAN', 'SUMURBOTO', 'TINJOMOYO'],
      'CANDISARI': ['CANDI', 'JATINGALEH', 'JOMBLANG', 'KALIWIRU', 'KARANGANYAR GUNUNG', 'TEGALSARI', 'WONOTINGAL'],
      'GAJAHMUNGKUR': ['BENDAN NGISOR', 'BENDUNGAN', 'GAJAHMUNGKUR', 'KARANGREJO', 'LEMPONGSARI', 'PETOMPON', 'SAMPANGAN', 'BENDAN DUWUR'],
      'GAYAMSARI': ['GAYAMSARI', 'KALIGAWE', 'PANDEAN LAMPER', 'SAMBIREJO', 'SAWAH BESAR', 'SIWALAN', 'TAMBAKREJO'],
      'GENUK': ['BANGETAYU KULON', 'BANGETAYU WETAN', 'BANJARDOWO', 'GEBANGSARI', 'GENUKSARI', 'KARANGROTO', 'KUDU', 'MUKTIHARJO LOR', 'PENGGARON LOR', 'SEMBUNGHARJO', 'TERBOYO KULON', 'TERBOYO WETAN', 'TRIMULYO'],
      'GUNUNGPATI': ['CEPOKO', 'GUNUNGPATI', 'JATIREJO', 'KALISEGORO', 'KANDRI', 'MANGUNSARI', 'NGIJO', 'NONGKOSAWIT', 'PAKINTELAN', 'PATEMON', 'PLALANGAN', 'PONGANGAN', 'SADENG', 'SEKARAN', 'SUKOREJO', 'SUMURREJO'],
      'MIJEN': ['BUBAKAN', 'CANGKIRAN', 'JATIBARANG', 'JATISARI', 'KARANGMALANG', 'KEDUNGPANE', 'MIJEN', 'NGADIRGO', 'PESANTREN', 'POLAMAN', 'PURWOSARI', 'TAMBANGAN', 'WONOLOPO', 'WONOPLUMBON'],
      'NGALIYAN': ['BAMBANKEREP', 'BERINGIN', 'GONDORIYO', 'KALIPANCUR', 'NGALIYAN', 'PODOREJO', 'PURWOYOSO', 'TAMBAKAJI', 'WONOSARI'],
      'PEDURUNGAN': ['GEMAH', 'KALICARI', 'MUKTIHARJO KIDUL', 'PALEBON', 'PEDURUNGAN KIDUL', 'PEDURUNGAN LOR', 'PEDURUNGAN TENGAH', 'PENGGARON KIDUL', 'PLAMONGAN SARI', 'TLOGOMULYO', 'TLOGOSARI KULON', 'TLOGOSARI WETAN'],
      'SEMARANG BARAT': ['BOJONG SALAMAN', 'BONGSARI', 'CABEAN', 'GISIKDRONO', 'KALIBANTENG KIDUL', 'KALIBANTENG KULON', 'KARANGAYU', 'KEMBANGARUM', 'KRAPYAK', 'MANYARAN', 'NGEMPLAK SIMONGAN', 'SALAMAN MLOYO', 'TAMBAKHARJO', 'TAWANGMAS', 'TAWANGSARI', 'TAMBAKREJO'],
      'SEMARANG SELATAN': ['BARUSARI', 'BULUSTALAN', 'LAMPER KIDUL', 'LAMPER LOR', 'LAMPER TENGAH', 'MUGASSARI', 'PLEBURAN', 'PETERONGAN', 'RANDUSARI', 'WONODRI'],
      'SEMARANG TENGAH': ['BANGUNHARJO', 'BRUMBUNGAN', 'GABAHAN', 'JAGALAN', 'KARANGKIDUL', 'KAUMAN', 'KEMBANGSARI', 'MIROTO', 'PANDANSARI', 'PEKUNDEN', 'PENDRIKAN KIDUL', 'PENDRIKAN LOR', 'PURWODINATAN', 'SEKAYU'],
      'SEMARANG TIMUR': ['BUGANGAN', 'KARANGTEMPEL', 'KARANGTURI', 'KEBONAGUNG', 'KEMIJEN', 'MLATIBARU', 'MLATIHARJO', 'REJOMULYO', 'REJOSARI', 'SARIREJO'],
      'SEMARANG UTARA': ['BANDARHARJO', 'BULU LOR', 'DADAPSARI', 'KUNINGAN', 'PANGGUNG KIDUL', 'PANGGUNG LOR', 'PLOMBOKAN', 'PURWOSARI', 'TANJUNG MAS'],
      'TEMBALANG': ['BULUSAN', 'KEDUNGMUNDU', 'KRAMAS', 'MANGUNHARJO', 'ROWOSARI', 'SAMBIROTO', 'SENDANGGUWO', 'SENDANGMULYO', 'TANDANG', 'TEMBALANG'],
      'TUGU': ['JERAKAH', 'KARANGANYAR', 'MANGKANG KULON', 'MANGKANG WETAN', 'MANGUNHARJO', 'RANDUGARUT', 'TUGUREJO']
    },
    'KOTA SURAKARTA': {
      'BANJARSARI': ['BANYUANYAR', 'GILINGAN', 'JOGLO', 'KADIPIRO', 'KESTALAN', 'KETELAN', 'MANAHAN', 'MANGKUBUMEN', 'NUSUKAN', 'PUNGGAWAN', 'SETABELAN', 'SUMBER', 'TIMURAN'],
      'JEBRES': ['GANDEKAN', 'JAGALAN', 'JEBRES', 'KEPATIHAN KULON', 'KEPATIHAN WETAN', 'MOJOSONGO', 'PUCANGSAWIT', 'PURWODININGRATAN', 'SEWU', 'SUDIROPRAJAN', 'TEGALHARJO'],
      'LAWEYAN': ['BUMI', 'JAJAR', 'KARANGASEM', 'LAWEYAN', 'PAJANG', 'PENUMPING', 'PURWOSARI', 'SONDAKAN', 'SRIWEDARI', 'TIPES', 'PANULARAN'],
      'PASAR KLIWON': ['BALUWARTI', 'GAJAHAN', 'JOYOSURAN', 'KAMPUNG BARU', 'KAUMAN', 'KEDUNG LUMBU', 'PASAR KLIWON', 'SANGKRAH', 'SEMANGGI', 'MOJO'],
      'SERENGAN': ['DANUKUSUMAN', 'JAYENGAN', 'JOYOTAKAN', 'KEMLAYAN', 'KRATONAN', 'SERENGAN', 'TIPES']
    },
    'KAB. BANJARNEGARA': ['BANJARMANGU', 'BANJARNEGARA', 'BATUR', 'BAWANG', 'KALIBENING', 'KARANGKOBAR', 'MADUKARA', 'MANDIRAJA', 'PAGEDONGAN', 'PAGENTAN', 'PANDANARUM', 'PEJAWARAN', 'PUNGGELAN', 'PURWANEGARA', 'PURWAREJA KLAMPOK', 'RAKIT', 'SIGALUH', 'SUSUKAN', 'WANADADI', 'WANAYASA'],
    'KAB. BANYUMAS': ['AJIBARANG', 'BANYUMAS', 'BATURADEN', 'CILONGOK', 'GUMELAR', 'JATILAWANG', 'KALIBAGOR', 'KARANGLEWAS', 'KEDUNGBANTENG', 'KEMBARAN', 'KEMRANJEN', 'LUMBIR', 'PATIKRAJA', 'PEKUNCEN', 'PURWOJATI', 'PURWOKERTO BARAT', 'PURWOKERTO SELATAN', 'PURWOKERTO TIMUR', 'PURWOKERTO UTARA', 'RAWALO', 'SOKARAJA', 'SOMAGEDE', 'SUMBANG', 'SUMPIUH', 'TAMBAK', 'WANGON', 'KALIBAGOR'],
    'KAB. BATANG': ['BANDAR', 'BATANG', 'BAWANG', 'BLADO', 'GRINGSING', 'KANDEMAN', 'LIMPUNG', 'PECALUNGAN', 'REBAN', 'SUBAH', 'TERSONO', 'TULIS', 'WARUNGASEM', 'WONOTUNGGAL', 'BANYUPUTIH'],
    'KAB. BLORA': ['BANJAREJO', 'BLORA', 'BOGOREJO', 'CEPU', 'JAPAH', 'JATI', 'JEPON', 'JIKEN', 'KEDUNGTUBAN', 'KRADENAN', 'KUNDURAN', 'NGAWEN', 'RANDUBLATUNG', 'SAMBONG', 'TODANAN', 'TUNJUNGAN'],
    'KAB. BOYOLALI': ['AMPEL', 'ANDONG', 'BANYUDONO', 'BOYOLALI', 'CEPOGO', 'JUWANGI', 'KARANGGEDE', 'KEMUSU', 'KLEGO', 'MOJOSONGO', 'MUSUK', 'NGEMPLAK', 'NOGOSARI', 'SAMBI', 'SAWIT', 'SELO', 'SIMO', 'TERAS', 'WONOSEGORO'],
    'KAB. BREBES': ['BANJARHARJO', 'BANTARKAWUNG', 'BREBES', 'BULAKAMBA', 'BUMIAYU', 'JATIBARANG', 'KERSANA', 'KETANGGUNGAN', 'LARANGAN', 'LOSARI', 'PAGUYANGAN', 'SALEM', 'SIRAMPOG', 'SONGGOM', 'TANJUNG', 'TONJONG', 'WANASARI'],
    'KAB. CILACAP': ['ADIPALA', 'BANTARSARI', 'BINANGUN', 'CILACAP SELATAN', 'CILACAP TENGAH', 'CILACAP UTARA', 'CIMANGGU', 'CIPARI', 'DAYEUHLUHUR', 'GANDRUNGMANGU', 'JERUKLEGI', 'KAMPUNG LAUT', 'KARANGPUCUNG', 'KAWUNGANTEN', 'KEDUNGREJA', 'KESUGIHAN', 'KROYA', 'MAJENANG', 'MAOS', 'NUSAWUNGU', 'PATIMUAN', 'SAMPANG', 'SIDAREJA', 'WANAREJA'],
    'KAB. DEMAK': ['BONANG', 'DEMAK', 'DEMPET', 'GAJAH', 'GUNTUR', 'KARANGANYAR', 'KARANGAWEN', 'KARANGTENGAH', 'KEBONAGUNG', 'MIJEN', 'MRANGGEN', 'SAYUNG', 'WEDUNG', 'WONOSALAM'],
    'KAB. GROBOGAN': ['BRATI', 'GABUS', 'GEYER', 'GODONG', 'GROBOGAN', 'GUBUG', 'KARANGRAYUNG', 'KEDUNGJATI', 'KLAMBU', 'KRADENAN', 'NGARINGAN', 'PENAWANGAN', 'PULOKULON', 'PURWODADI', 'TANGGUNGHARJO', 'TAWANGHARJO', 'TEGOWANU', 'TOROH', 'WIROSARI'],
    'KAB. JEPARA': ['BANGSRI', 'BATEALIT', 'DONOROJO', 'JEPARA', 'KALINYAMATAN', 'KARIMUNJAWA', 'KEDUNG', 'KELING', 'KEMBANG', 'MAYONG', 'MLONGGO', 'NALUMSARI', 'PAKIS AJI', 'PECANGAAN', 'TAHUNAN', 'WELAHAN'],
    'KAB. KARANGANYAR': ['COLOMADU', 'GONDANGREJO', 'JATEN', 'JATIPURO', 'JATIYOSO', 'JUMANTONO', 'JUMAPOLO', 'KARANGANYAR', 'KARANGPANDAN', 'KEBAKKRAMAT', 'KERJO', 'MATESIH', 'MOJOGEDANG', 'NGARGOYOSO', 'TASIKMADU', 'TAWANGMANGU'],
    'KAB. KEBUMEN': ['ADIMULYO', 'AMBAL', 'AYAH', 'BUAYAN', 'BULUSPESANTREN', 'GOMBONG', 'KARANGANYAR', 'KARANGGAYAM', 'KARANGSAMBUNG', 'KEBUMEN', 'KLIRONG', 'KUTOWINANGUN', 'KUWARASAN', 'MIRIT', 'PADURESO', 'PEJAGOAN', 'PETANAHAN', 'PONCOWARNO', 'PREMBUN', 'PURING', 'ROWOKELE', 'SADANG', 'SEMPOR', 'SRUWENG', 'BONOROWO', 'ALIAN'],
    'KAB. KENDAL': ['BOJA', 'BRANGSONG', 'CEPIRING', 'GEMUH', 'KALIWUNGU', 'KALIWUNGU SELATAN', 'KANGKUNG', 'KENDAL', 'LIMBANGAN', 'NGAMPEL', 'PAGERUYUNG', 'PATEAN', 'PATEBON', 'PLANTUNGAN', 'RINGINARUM', 'ROWOSARI', 'SINGOROJO', 'SUKOREJO', 'WELERI'],
    'KAB. KLATEN': ['BAYAT', 'CAWAS', 'CEPER', 'DELANGGU', 'GANTIWARNO', 'JATINOM', 'JOGONALAN', 'JUWIRING', 'KALIKOTES', 'KARANGANOM', 'KARANGDOWO', 'KARANGNONGKO', 'KEBONARUM', 'KEMALANG', 'KLATEN SELATAN', 'KLATEN TENGAH', 'KLATEN UTARA', 'MANISRENGGO', 'NGAWEN', 'PEDAN', 'POLANHARJO', 'PRAMBANAN', 'TRUCUK', 'TULUNG', 'WEDI', 'WONOSARI'],
    'KAB. KUDUS': ['BAE', 'DAWE', 'GEBOG', 'JATI', 'JEKULO', 'KALIWUNGU', 'KOTA KUDUS', 'MEJOBO', 'UNDAAN'],
    'KAB. MAGELANG': ['BANDONGAN', 'BOROBUDUR', 'CANDIMULYO', 'DUKUN', 'GRABAG', 'KAJORAN', 'KALIANGKRIK', 'MERTOYUDAN', 'MUNGKID', 'MUNTILAN', 'NGABLAK', 'NGLUWAR', 'PAKIS', 'SALAM', 'SALAMAN', 'SAWANGAN', 'SECANG', 'SRUMBUNG', 'TEGALREJO', 'TEMPURAN', 'WINDUSARI'],
    'KAB. PATI': ['BATANGAN', 'CLUWAK', 'DUKUHSETI', 'GABUS', 'GEMBONG', 'GUNUNGWUNGKAL', 'JAKEN', 'JAKENAN', 'JUWANA', 'KAYEN', 'MARGOREJO', 'MARGOYOSO', 'PATI', 'PUCAKWANGI', 'SUKOLILO', 'TAMBAKROMO', 'TAYU', 'TLOGOWUNGU', 'TRANGKIL', 'WEDARIJAKSA', 'WINONG'],
    'KAB. PEKALONGAN': ['BOJONG', 'BUARAN', 'DORO', 'KAJEN', 'KANDANGSERANG', 'KARANGANYAR', 'KARANGDADAP', 'KEDUNGWUNI', 'KESESI', 'LEBAKBARANG', 'PANINGGARAN', 'PETUNGKRIYONO', 'SIWALAN', 'SRAGI', 'TALUN', 'TIRTO', 'WIRADESA', 'WONOKERTO', 'WONOPRINGGO'],
    'KAB. PEMALANG': ['AMPELGADING', 'BANTARBOLANG', 'BELIK', 'BODEH', 'COMAL', 'MOGA', 'PEMALANG', 'PETARUKAN', 'PULOSARI', 'RANDUDONGKAL', 'TAMAN', 'ULUJAMI', 'WARUNGPRING', 'WATUKUMPUL'],
    'KAB. PURBALINGGA': ['BOBOTSARI', 'BOJONGSARI', 'BUKATEJA', 'KALIGONDANG', 'KALIMANAH', 'KARANGANYAR', 'KARANGJAMBU', 'KARANGMONCOL', 'KARANGREJA', 'KEJOBONG', 'KEMANGKON', 'KERTANEGARA', 'KUTASARI', 'MREBET', 'PADAMARA', 'PENGADEGAN', 'PURBALINGGA', 'REMBANG'],
    'KAB. PURWOREJO': ['BAGELEN', 'BANYUURIP', 'BAYAN', 'BENER', 'BRUNO', 'BUTUH', 'GEBANG', 'GRABAG', 'KALIGESING', 'KEMIRI', 'LOANO', 'NGOMBOL', 'PITURUH', 'PURWODADI', 'PURWOREJO'],
    'KAB. REMBANG': ['BULU', 'GUNEM', 'KALIORI', 'KRAGAN', 'LASEM', 'PAMOTAN', 'PANCUR', 'REMBANG', 'SALE', 'SARANG', 'SEDAN', 'SLUKE', 'SULANG', 'SUMBER'],
    'KAB. SEMARANG': ['AMBARAWA', 'BANCAK', 'BANDUNGAN', 'BANYUBIRU', 'BAWEN', 'BERGAS', 'BRINGIN', 'GETASAN', 'JAMBU', 'KALIWUNGU', 'PABELAN', 'PRINGAPUS', 'SUMOWONO', 'SURUH', 'SUSUKAN', 'TENGARAN', 'TUNTANG', 'UNGARAN BARAT', 'UNGARAN TIMUR'],
    'KAB. SRAGEN': ['GEMOLONG', 'GESI', 'GONDANG', 'JENAR', 'KALIJAMBE', 'KARANGMALANG', 'KEDAWUNG', 'MASARAN', 'MIRI', 'MONDOKAN', 'NGRAMPAL', 'PLUPUH', 'SAMBIREJO', 'SAMBUNGMACAN', 'SIDOHARJO', 'SRAGEN', 'SUKODONO', 'SUMBERLAWANG', 'TANGEN', 'TANON'],
    'KAB. SUKOHARJO': ['BAKI', 'BENDOSARI', 'GATAK', 'GROGOL', 'KARTASURA', 'MOJOLABAN', 'NGUTER', 'POLOKARTO', 'SUKOHARJO', 'TAWANGSARI', 'WERU', 'BULU'],
    'KAB. TEGAL': ['ADIWERNA', 'BALAPULANG', 'BOJONG', 'BUMIJAWA', 'DUKUHTURI', 'DUKUHWARU', 'JATINEGARA', 'KEDUNGBANTENG', 'KRAMAT', 'LEBAKSIU', 'MARGASARI', 'PAGERBARANG', 'PANGKAH', 'SLAWI', 'SURADADI', 'TALANG', 'TARUB', 'WARUREJA'],
    'KAB. TEMANGGUNG': ['BANSARI', 'BEJEN', 'BULU', 'CANDIROTO', 'GEMAWANG', 'JUMO', 'KALORAN', 'KANDANGAN', 'KEDU', 'KLEDUNG', 'KRANGGAN', 'NGADIREJO', 'PARAKAN', 'PRINGSURAT', 'SELOPAMPANG', 'TEMANGGUNG', 'TEMBARAK', 'TLOGOMULYO', 'TRETEP', 'WONOBOYO'],
    'KAB. WONOGIRI': ['BATURETNO', 'BATUWARNO', 'BULUKERTO', 'EROMOKO', 'GIRIMARTO', 'GIRITONTRO', 'GIRIWOYO', 'JATIPURNO', 'JATIROTO', 'JATISRONO', 'KARANGTENGAH', 'KISMANTORO', 'MANYARAN', 'NGADIROJO', 'NGUNTORONADI', 'PARANGGUPITO', 'PRACIMANTORO', 'PURWANTORO', 'SELOGIRI', 'SIDOHARJO', 'SLOGOHIMO', 'TIRTOMOYO', 'WONOGIRI', 'WURYANTORO', 'PUHPELEM'],
    'KAB. WONOSOBO': ['GARUNG', 'KALIBAWANG', 'KALIKAJAR', 'KALIWIRO', 'KEJAJAR', 'KEPIL', 'KERTEK', 'LEKSONO', 'MOJOTENGAH', 'SAPURAN', 'SELOMERTO', 'SUKOHARJO', 'WADASLINTANG', 'WATUMALANG', 'WONOSOBO'],
    'KOTA MAGELANG': ['MAGELANG SELATAN', 'MAGELANG TENGAH', 'MAGELANG UTARA'],
    'KOTA PEKALONGAN': ['PEKALONGAN BARAT', 'PEKALONGAN SELATAN', 'PEKALONGAN TIMUR', 'PEKALONGAN UTARA'],
    'KOTA SALATIGA': ['ARGOMULYO', 'SIDOMUKTI', 'SIDOREJO', 'TINGKIR'],
    'KOTA TEGAL': ['MARGADANA', 'TEGAL BARAT', 'TEGAL SELATAN', 'TEGAL TIMUR']
  },

  /* ====================================================================
     JAWA BARAT — 27 Kabupaten/Kota (lengkap)
     ==================================================================== */
  'JAWA BARAT': {
    'KOTA BANDUNG': {
      'ANDIR': ['CAMPAKA', 'CIROYOM', 'DUNGUSCARIANG', 'GARUDA', 'KEBON JERUK', 'MALEBER'],
      'ANTAPANI': ['ANTAPANI KIDUL', 'ANTAPANI KULON', 'ANTAPANI TENGAH', 'ANTAPANI WETAN'],
      'ARCAMANIK': ['CISARANTEN BINA HARAPAN', 'CISARANTEN ENDAH', 'CISARANTEN KULON', 'SUKAMISKIN'],
      'ASTANAANYAR': ['CIBADAK', 'JAMIKA', 'KARANG ANYAR', 'KARASAK', 'NYENGSERET', 'PANJUNAN'],
      'BABAKAN CIPARAY': ['BABAKAN', 'BABAKAN CIPARAY', 'CIRANGRANG', 'MARGAHAYU UTARA', 'MARGASUKA', 'SUKAHAJI'],
      'BANDUNG KIDUL': ['BATUNUNGGAL', 'KUJANGSARI', 'MENGGER', 'WATES'],
      'BANDUNG KULON': ['CARINGIN', 'CIBUNTU', 'CIGONDEWAH KALER', 'CIGONDEWAH KIDUL', 'CIGONDEWAH RAHAYU', 'CIJERAH', 'GEMPOLSARI', 'WARUNG MUNCANG'],
      'BANDUNG WETAN': ['CIHAPIT', 'CITARUM', 'TAMANSARI'],
      'BATUNUNGGAL': ['BINONG', 'CIBANGKONG', 'GUMURUH', 'KACAPIRING', 'KEBON GEDANG', 'KEBON WARU', 'MALEER', 'SAMOJA'],
      'BOJONGLOA KALER': ['BABAKAN ASIH', 'BABAKAN TAROGONG', 'JAMIKA', 'KOPO', 'SUKA ASIH'],
      'BOJONGLOA KIDUL': ['CIBADUYUT', 'CIBADUYUT KIDUL', 'CIBADUYUT WETAN', 'KEBON LEGA', 'MEKARWANGI', 'SITUSAEUR'],
      'BUAHBATU': ['CIJAWURA', 'JATISARI', 'MARGASARI', 'SEKEJATI'],
      'CIBEUNYING KALER': ['CIGADUNG', 'CIHAURGEULIS', 'NEGLASARI', 'SUKALUYU'],
      'CIBEUNYING KIDUL': ['CICADAS', 'CIKUTRA', 'PADASUKA', 'PASIRLAYUNG', 'SUKAMAJU', 'SUKAPADA'],
      'CIBIRU': ['CIPADUNG', 'CIPADUNG KIDUL', 'CIPADUNG WETAN', 'PALASARI', 'PASIR BIRU'],
      'CICENDO': ['ARJUNA', 'HUSEN SASTRANEGARA', 'PAJAJARAN', 'PAMOYANAN', 'SUKARAJA', 'PASIR KALIKI'],
      'CIDADAP': ['CIUMBULEUIT', 'HEGARMANAH', 'LEDENG'],
      'COBLONG': ['CIPAGANTI', 'DAGO', 'LEBAK GEDE', 'LEBAK SILIWANGI', 'SADANG SERANG', 'SEKELOA'],
      'GEDEBAGE': ['CIMENCRANG', 'CISARANTEN KIDUL', 'RANCABOLANG', 'RANCANUMPANG'],
      'KIARACONDONG': ['BABAKAN SARI', 'BABAKAN SURABAYA', 'CICAHEUM', 'KEBON JAYANTI', 'KEBUN KANGKUNG', 'SUKAPURA'],
      'LENGKONG': ['BURANGRANG', 'CIJAGRA', 'CIKAWAO', 'LINGKAR SELATAN', 'MALABAR', 'PALEDANG', 'TURANGGA'],
      'MANDALAJATI': ['JATIHANDAP', 'KARANG PAMULANG', 'PASIR IMPUN', 'SINDANGJAYA'],
      'PANYILEUKAN': ['MEKARMULYA'],
      'RANCASARI': ['CIPAMOKOLAN', 'DERWATI', 'MANJAHLEGA', 'MEKAR JAYA'],
      'REGOL': ['ANCOL', 'BALONGGEDE', 'CIATEUL', 'CIGERELENG', 'CISEUREUH', 'PASIRLUYU', 'PUNGKUR'],
      'SUKAJADI': ['CIPEDES', 'PASTEUR', 'SUKABUNGAH', 'SUKAGALIH', 'SUKAWARNA'],
      'SUKASARI': ['GEGERKALONG', 'ISOLA', 'SARIJADI', 'SUKARASA'],
      'SUMUR BANDUNG': ['BRAGA', 'KEBON PISANG', 'MERDEKA', 'BABAKAN CIAMIS'],
      'UJUNGBERUNG': ['CIGENDING', 'PASANGGRAHAN', 'PASIR ENDAH', 'PASIR JATI', 'PASIR WANGI']
    },
    'KOTA BEKASI': {
      'BANTAR GEBANG': ['BANTAR GEBANG', 'CIKETING UDIK', 'CIKIWUL', 'SUMUR BATU'],
      'BEKASI BARAT': ['BINTARA', 'BINTARA JAYA', 'JAKASAMPURNA', 'KOTA BARU', 'KRANJI'],
      'BEKASI SELATAN': ['JAKA MULYA', 'JAKA SETIA', 'KAYURINGIN JAYA', 'MARGA JAYA', 'PEKAYON JAYA'],
      'BEKASI TIMUR': ['ARENJAYA', 'BEKASI JAYA', 'DUREN JAYA', 'MARGAHAYU'],
      'BEKASI UTARA': ['HARAPAN BARU', 'HARAPAN JAYA', 'KALI ABANG TENGAH', 'MARGA MULYA', 'PERWIRA', 'TELUK PUCUNG'],
      'JATIASIH': ['JATI ASIH', 'JATI KRAMAT', 'JATI LUHUR', 'JATI MEKAR', 'JATI RASA', 'JATISARI'],
      'JATISAMPURNA': ['JATIKARYA', 'JATIRADEN', 'JATIRANGGA', 'JATIRANGGON', 'JATISAMPURNA'],
      'MEDAN SATRIA': ['HARAPAN MULYA', 'KALI BARU', 'MEDAN SATRIA', 'PEJUANG'],
      'MUSTIKA JAYA': ['CIMUNING', 'MUSTIKA JAYA', 'MUSTIKASARI', 'PEDURENAN'],
      'PONDOK GEDE': ['JATI BENING', 'JATI BENING BARU', 'JATI CEMPAKA', 'JATI MAKMUR', 'JATI WARINGIN'],
      'PONDOK MELATI': ['JATI MELATI', 'JATI MURNI', 'JATI RAHAYU', 'JATI WARNA'],
      'RAWALUMBU': ['BOJONG MENTENG', 'BOJONG RAWALUMBU', 'PENGASINAN', 'SEPANJANG JAYA']
    },
    'KOTA DEPOK': {
      'BEJI': ['BEJI', 'BEJI TIMUR', 'KEMIRIMUKA', 'KUKUSAN', 'PONDOK CINA', 'TANAH BARU'],
      'BOJONGSARI': ['BOJONGSARI', 'BOJONGSARI BARU', 'CURUG', 'DUREN MEKAR', 'DUREN SERIBU', 'PONDOK PETIR', 'SERUA'],
      'CILODONG': ['CILODONG', 'JATIMULYA', 'KALIBARU', 'SUKAMAJU', 'SUKAMAJU BARU'],
      'CIMANGGIS': ['CISALAK PASAR', 'CURUG', 'HARJAMUKTI', 'MEKARSARI', 'PASIR GUNUNG SELATAN', 'TUGU'],
      'CINERE': ['CINERE', 'GANDUL', 'PANGKALAN JATI', 'PANGKALAN JATI BARU'],
      'CIPAYUNG': ['BOJONG PONDOK TERONG', 'CIPAYUNG', 'CIPAYUNG JAYA', 'PONDOK JAYA', 'RATU JAYA'],
      'LIMO': ['GROGOL', 'KRUKUT', 'LIMO', 'MERUYUNG'],
      'PANCORAN MAS': ['DEPOK', 'DEPOK JAYA', 'MAMPANG', 'PANCORAN MAS', 'RANGKAPAN JAYA', 'RANGKAPAN JAYA BARU'],
      'SAWANGAN': ['BEDAHAN', 'CINANGKA', 'KEDAUNG', 'PASIR PUTIH', 'PENGASINAN', 'SAWANGAN', 'SAWANGAN BARU'],
      'SUKMAJAYA': ['ABADIJAYA', 'BAKTIJAYA', 'CISALAK', 'MEKARJAYA', 'SUKAMAJU', 'TIRTAJAYA'],
      'TAPOS': ['CILANGKAP', 'CIMPAEUN', 'JATIJAJAR', 'LEUWINANGGUNG', 'SUKATANI', 'TAPOS']
    },
    'KAB. BANDUNG': ['ARJASARI', 'BALEENDAH', 'BANJARAN', 'BOJONGSOANG', 'CANGKUANG', 'CICALENGKA', 'CIKANCUNG', 'CILENGKRANG', 'CILEUNYI', 'CIMAUNG', 'CIMENYAN', 'CIPARAY', 'CIWIDEY', 'DAYEUHKOLOT', 'IBUN', 'KATAPANG', 'KERTASARI', 'KUTAWARINGIN', 'MAJALAYA', 'MARGAASIH', 'MARGAHAYU', 'NAGREG', 'PACET', 'PAMEUNGPEUK', 'PANGALENGAN', 'PASEH', 'PASIRJAMBU', 'RANCABALI', 'RANCAEKEK', 'SOLOKAN JERUK', 'SOREANG'],
    'KAB. BANDUNG BARAT': ['BATUJAJAR', 'CIHAMPELAS', 'CIKALONG WETAN', 'CILILIN', 'CIPATAT', 'CIPEUNDEUY', 'CISARUA', 'GUNUNG HALU', 'LEMBANG', 'NGAMPRAH', 'PADALARANG', 'PARONGPONG', 'RONGGA', 'SAGULING', 'SINDANGKERTA', 'CIPONGKOR'],
    'KAB. BEKASI': ['BABELAN', 'BOJONGMANGU', 'CABANGBUNGIN', 'CIBARUSAH', 'CIBITUNG', 'CIKARANG BARAT', 'CIKARANG PUSAT', 'CIKARANG SELATAN', 'CIKARANG TIMUR', 'CIKARANG UTARA', 'KARANGBAHAGIA', 'KEDUNGWARINGIN', 'MUARAGEMBONG', 'PEBAYURAN', 'SERANG BARU', 'SETU', 'SUKAKARYA', 'SUKATANI', 'SUKAWANGI', 'TAMBELANG', 'TAMBUN SELATAN', 'TAMBUN UTARA', 'TARUMAJAYA'],
    'KAB. BOGOR': ['BABAKAN MADANG', 'BOJONGGEDE', 'CARINGIN', 'CIAMPEA', 'CIAWI', 'CIBINONG', 'CIBUNGBULANG', 'CIGOMBONG', 'CIGUDEG', 'CIJERUK', 'CILEUNGSI', 'CIOMAS', 'CISARUA', 'CISEENG', 'CITEUREUP', 'DRAMAGA', 'GUNUNG PUTRI', 'GUNUNG SINDUR', 'JASINGA', 'JONGGOL', 'KEMANG', 'KLAPANUNGGAL', 'LEUWILIANG', 'LEUWISADENG', 'MEGAMENDUNG', 'NANGGUNG', 'PAMIJAHAN', 'PARUNG', 'PARUNG PANJANG', 'RANCABUNGUR', 'RUMPIN', 'SUKAJAYA', 'SUKAMAKMUR', 'SUKARAJA', 'TAJURHALANG', 'TAMANSARI', 'TANJUNGSARI', 'TENJO', 'TENJOLAYA'],
    'KAB. CIAMIS': ['BAREGBEG', 'BANJARANYAR', 'CIAMIS', 'CIDOLOG', 'CIHAURBEUTI', 'CIJEUNGJING', 'CIKONENG', 'CIMARAGAS', 'CIPAKU', 'CISAGA', 'JATINAGARA', 'KAWALI', 'LAKBOK', 'LUMBUNG', 'PAMARICAN', 'PANAWANGAN', 'PANJALU', 'PANUMBANGAN', 'PURWADADI', 'RAJADESA', 'RANCAH', 'SADANANYA', 'SINDANGKASIH', 'SUKADANA', 'SUKAMANTRI', 'TAMBAKSARI'],
    'KAB. CIANJUR': ['AGRABINTA', 'BOJONGPICUNG', 'CAMPAKA', 'CAMPAKAMULYA', 'CIANJUR', 'CIBEBER', 'CIBINONG', 'CIDAUN', 'CIKADU', 'CIKALONGKULON', 'CILAKU', 'CIPANAS', 'CIRANJANG', 'CUGENANG', 'GEKBRONG', 'HAURWANGI', 'KADUPANDAK', 'KARANGTENGAH', 'LELES', 'MANDE', 'NARINGGUL', 'PACET', 'PAGELARAN', 'PASIRKUDA', 'SINDANGBARANG', 'SUKALUYU', 'SUKANAGARA', 'SUKARESMI', 'TAKOKAK', 'TANGGEUNG', 'WARUNGKONDANG'],
    'KAB. CIREBON': ['ARJAWINANGUN', 'ASTANAJAPURA', 'BABAKAN', 'BEBER', 'CIWARINGIN', 'DEPOK', 'DUKUPUNTANG', 'GEBANG', 'GEGESIK', 'GEMPOL', 'GREGED', 'GUNUNG JATI', 'JAMBLANG', 'KALIWEDI', 'KAPETAKAN', 'KARANGSEMBUNG', 'KARANGWARENG', 'KEDAWUNG', 'KLANGENAN', 'LEMAHABANG', 'LOSARI', 'MUNDU', 'PABEDILAN', 'PABUARAN', 'PALIMANAN', 'PANGENAN', 'PANGURAGAN', 'PASALEMAN', 'PLERED', 'PLUMBON', 'SEDONG', 'SUMBER', 'SURANENGGALA', 'SUSUKAN', 'SUSUKAN LEBAK', 'TALUN', 'TENGAH TANI', 'WALED', 'WERU'],
    'KAB. GARUT': ['BALUBUR LIMBANGAN', 'BANJARWANGI', 'BANYURESMI', 'BAYONGBONG', 'BUNGBULANG', 'CARINGIN', 'CIBALONG', 'CIBATU', 'CIBIUK', 'CIGEDUG', 'CIHURIP', 'CIKAJANG', 'CIKELET', 'CILAWU', 'CISEWU', 'CISOMPET', 'CISURUPAN', 'GARUT KOTA', 'KADUNGORA', 'KARANGPAWITAN', 'KARANGTENGAH', 'KERSAMANAH', 'LELES', 'LEUWIGOONG', 'MALANGBONG', 'MEKARMUKTI', 'PAKENJENG', 'PAMEUNGPEUK', 'PANGATIKAN', 'PASIRWANGI', 'PEUNDEUY', 'SAMARANG', 'SINGAJAYA', 'SUCINARAJA', 'SUKAWENING', 'TALEGONG', 'TAROGONG KALER', 'TAROGONG KIDUL', 'WANARAJA'],
    'KAB. INDRAMAYU': ['ANJATAN', 'ARAHAN', 'BALONGAN', 'BANGODUA', 'BONGAS', 'CANTIGI', 'CIKEDUNG', 'GABUSWETAN', 'GANTAR', 'HAURGEULIS', 'INDRAMAYU', 'JATIBARANG', 'JUNTINYUAT', 'KANDANGHAUR', 'KEDOKAN BUNDER', 'KERTASEMAYA', 'KRANGKENG', 'KROYA', 'LELEA', 'LOHBENER', 'LOSARANG', 'PASEKAN', 'PATROL', 'SINDANG', 'SLIYEG', 'SUKAGUMIWANG', 'SUKRA', 'TERISI', 'TUKDANA', 'WIDASARI'],
    'KAB. KARAWANG': ['BANYUSARI', 'BATUJAYA', 'CIAMPEL', 'CIBUAYA', 'CIKAMPEK', 'CILAMAYA KULON', 'CILAMAYA WETAN', 'CILEBAR', 'JATISARI', 'JAYAKERTA', 'KARAWANG BARAT', 'KARAWANG TIMUR', 'KLARI', 'KOTABARU', 'KUTAWALUYA', 'LEMAHABANG', 'MAJALAYA', 'PAKISJAYA', 'PANGKALAN', 'PEDES', 'PURWASARI', 'RAWAMERTA', 'RENGASDENGKLOK', 'TALAGASARI', 'TEGALWARU', 'TELUKJAMBE BARAT', 'TELUKJAMBE TIMUR', 'TEMPURAN', 'TIRTAJAYA', 'TIRTAMULYA'],
    'KAB. KUNINGAN': ['CIAWIGEBANG', 'CIBEUREUM', 'CIBINGBIN', 'CIDAHU', 'CIGANDAMEKAR', 'CIGUGUR', 'CILEBAK', 'CILIMUS', 'CIMAHI', 'CINIRU', 'CIPICUNG', 'CIWARU', 'DARMA', 'GARAWANGI', 'HANTARA', 'JALAKSANA', 'JAPARA', 'KADUGEDE', 'KALIMANGGIS', 'KARANGKANCANA', 'KRAMATMULYA', 'KUNINGAN', 'LEBAKWANGI', 'LURAGUNG', 'MALEBER', 'MANDIRANCAN', 'NUSAHERANG', 'PANCALANG', 'PASAWAHAN', 'SELAJAMBE', 'SINDANGAGUNG', 'SUBANG'],
    'KAB. MAJALENGKA': ['ARGAPURA', 'BANJARAN', 'BANTARUJEG', 'CIGASONG', 'CIKIJING', 'CINGAMBUL', 'DAWUAN', 'JATITUJUH', 'JATIWANGI', 'KADIPATEN', 'KASOKANDEL', 'KERTAJATI', 'LEMAHSUGIH', 'LEUWIMUNDING', 'LIGUNG', 'MAJA', 'MAJALENGKA', 'MALAUSMA', 'PALASAH', 'PANYINGKIRAN', 'RAJAGALUH', 'SINDANG', 'SINDANGWANGI', 'SUKAHAJI', 'SUMBERJAYA', 'TALAGA'],
    'KAB. PANGANDARAN': ['CIGUGUR', 'CIJULANG', 'CIMERAK', 'KALIPUCANG', 'LANGKAPLANCAR', 'MANGUNJAYA', 'PADAHERANG', 'PANGANDARAN', 'PARIGI', 'SIDAMULIH'],
    'KAB. PURWAKARTA': ['BABAKANCIKAO', 'BOJONG', 'BUNGURSARI', 'CAMPAKA', 'CIBATU', 'DARANGDAN', 'JATILUHUR', 'KIARAPEDES', 'MANIIS', 'PASAWAHAN', 'PLERED', 'POND SALAM', 'PURWAKARTA', 'SUKASARI', 'SUKATANI', 'TEGALWARU', 'WANAYASA'],
    'KAB. SUBANG': ['BINONG', 'BLANAKAN', 'CIASEM', 'CIATER', 'CIBOGO', 'CIJAMBE', 'CIKAUM', 'CIPEUNDEUY', 'CIPUNAGARA', 'CISALAK', 'COMPRENG', 'DAWUAN', 'JALANCAGAK', 'KALIJATI', 'KASOMALANG', 'LEGONKULON', 'PABUARAN', 'PAGADEN', 'PAGADEN BARAT', 'PAMANUKAN', 'PATOKBEUSI', 'PURWADADI', 'PUSAKAJAYA', 'PUSAKANAGARA', 'SAGALAHERANG', 'SERANGPANJANG', 'SUBANG', 'SUKASARI', 'TAMBAKDAHAN', 'TANJUNGSIANG'],
    'KAB. SUKABUMI': ['BANTARGADUNG', 'BOJONGGENTENG', 'CARINGIN', 'CIAMBAR', 'CIBADAK', 'CIBITUNG', 'CICANTAYAN', 'CICURUG', 'CIDADAP', 'CIDAHU', 'CIEMAS', 'CIKAKAK', 'CIKEMBAR', 'CIKIDANG', 'CIMANGGU', 'CIRACAP', 'CISAAT', 'CISOLOK', 'CURUGKEMBAR', 'GEGERBITUNG', 'GUNUNGGURUH', 'JAMPANGKULON', 'JAMPANGTENGAH', 'KABANDUNGAN', 'KADUDAMPIT', 'KALAPANUNGGAL', 'KALIBUNDER', 'KEBONPEDES', 'LENGKONG', 'NAGRAK', 'NYALINDUNG', 'PABUARAN', 'PARAKANSALAK', 'PARUNGKUDA', 'PURABAYA', 'SAGARANTEN', 'SIMPENAN', 'SUKABUMI', 'SUKALARANG', 'SUKARAJA', 'SURADE', 'TEGALBULEUD', 'WALURAN', 'WARUNGKIARA'],
    'KAB. SUMEDANG': ['BUAHDUA', 'CIBUGEL', 'CIMALAKA', 'CIMANGGUNG', 'CISARUA', 'CISITU', 'CONGGEANG', 'DARMARAJA', 'GANEAS', 'JATIGEDE', 'JATINANGOR', 'JATINUNGGAL', 'PAMULIHAN', 'PASEH', 'RANCAKALONG', 'SITURAJA', 'SUKASARI', 'SUMEDANG SELATAN', 'SUMEDANG UTARA', 'SURIAN', 'TANJUNGKERTA', 'TANJUNGMEDAR', 'TANJUNGSARI', 'TOMO', 'UJUNGJAYA', 'WADO'],
    'KAB. TASIKMALAYA': ['BANTARKALONG', 'BOJONGASIH', 'BOJONGGAMBIR', 'CIAWI', 'CIBALONG', 'CIGALONTANG', 'CIKALONG', 'CIKATOMAS', 'CINEAM', 'CIPATUJAH', 'CISAYONG', 'CULAMEGA', 'GUNUNGTANJUNG', 'JAMANIS', 'JATIWARAS', 'KADIPATEN', 'KARANGJAYA', 'KARANGNUNGGAL', 'LEUWISARI', 'MANONJAYA', 'MANGUNREJA', 'PADAKEMBANG', 'PAGERAGEUNG', 'PANCATENGAH', 'PARUNGPONTENG', 'PUSPAHIANG', 'RAJAPOLAH', 'SALAWU', 'SALOPA', 'SARIWANGI', 'SINGAPARNA', 'SODONGHILIR', 'SUKAHENING', 'SUKARAJA', 'SUKARAME', 'SUKARATU', 'SUKARESIK', 'TANJUNGJAYA', 'TARAJU'],
    'KOTA BANJAR': ['BANJAR', 'LANGENSARI', 'PATARUMAN', 'PURWAHARJA'],
    'KOTA BOGOR': ['BOGOR BARAT', 'BOGOR SELATAN', 'BOGOR TENGAH', 'BOGOR TIMUR', 'BOGOR UTARA', 'TANAH SAREAL'],
    'KOTA CIMAHI': ['CIMAHI SELATAN', 'CIMAHI TENGAH', 'CIMAHI UTARA'],
    'KOTA CIREBON': ['HARJAMUKTI', 'KEJAKSAN', 'KESAMBI', 'LEMAHWUNGKUK', 'PEKALIPAN'],
    'KOTA SUKABUMI': ['BAROS', 'CIBEUREUM', 'CIKOLE', 'CITAMIANG', 'GUNUNG PUYUH', 'LEMBURSITU', 'WARUDOYONG'],
    'KOTA TASIKMALAYA': ['BUNGURSARI', 'CIBEUREUM', 'CIHIDEUNG', 'CIPEDES', 'INDIHIANG', 'KAWALU', 'MANGKUBUMI', 'PURBARATU', 'TAMANSARI', 'TAWANG']
  },

  /* ====================================================================
     DKI JAKARTA — 6 Kabupaten/Kota Administrasi (kecamatan lengkap)
     ==================================================================== */
  'DKI JAKARTA': {
    'KAB. ADM. KEP. SERIBU': {
      'KEPULAUAN SERIBU SELATAN': ['PULAU PARI', 'PULAU TIDUNG', 'PULAU UNTUNG JAWA'],
      'KEPULAUAN SERIBU UTARA': ['PULAU HARAPAN', 'PULAU KELAPA', 'PULAU PANGGANG']
    },
    'KOTA ADM. JAKARTA BARAT': {
      'CENGKARENG': ['CENGKARENG BARAT', 'CENGKARENG TIMUR', 'DURI KOSAMBI', 'KAPUK', 'KEDAUNG KALI ANGKE', 'RAWA BUAYA'],
      'GROGOL PETAMBURAN': ['GROGOL', 'JELAMBAR', 'JELAMBAR BARU', 'TANJUNG DUREN SELATAN', 'TANJUNG DUREN UTARA', 'TOMANG', 'WIJAYA KUSUMA'],
      'KALI DERES': ['KALIDERES', 'KAMAL', 'PEGADUNGAN', 'SEMANAN', 'TEGAL ALUR'],
      'KEBON JERUK': ['DURI KEPA', 'KEBON JERUK', 'KEDOYA SELATAN', 'KEDOYA UTARA', 'KELAPA DUA', 'SUKABUMI SELATAN', 'SUKABUMI UTARA'],
      'KEMBANGAN': ['JOGLO', 'KEMBANGAN SELATAN', 'KEMBANGAN UTARA', 'MERUYA SELATAN', 'MERUYA UTARA', 'SRENGSENG'],
      'PALMERAH': ['JATI PULO', 'KEMANGGISAN', 'KOTA BAMBU SELATAN', 'KOTA BAMBU UTARA', 'PALMERAH', 'SLIPI'],
      'TAMAN SARI': ['ANGKE', 'GLODOK', 'JEMBATAN BESAR', 'JEMBATAN LIMA', 'KEAGUNGAN', 'KRUKUT', 'MANGGA BESAR', 'MAPHAR', 'PINANGSIA', 'TAMAN SARI', 'TANGKI'],
      'TAMBORA': ['ANGKE', 'DURI SELATAN', 'DURI UTARA', 'JEMBATAN BESI', 'KALI ANYAR', 'KRENDANG', 'PEKOJAN', 'ROA MALAKA', 'TAMBORA', 'TANAH SEREAL']
    },
    'KOTA ADM. JAKARTA PUSAT': {
      'CEMPAKA PUTIH': ['CEMPAKA PUTIH BARAT', 'CEMPAKA PUTIH TIMUR', 'RAWASARI'],
      'GAMBIR': ['CIDENG', 'DURI PULO', 'GAMBIR', 'KEBON KELAPA', 'PETOJO SELATAN', 'PETOJO UTARA'],
      'JOHAR BARU': ['GALUR', 'JOHAR BARU', 'KAMPUNG RAWA', 'TANAH TINGGI'],
      'KEMAYORAN': ['CEMPAKA BARU', 'GUNUNG SAHARI SELATAN', 'HARAPAN MULIA', 'KEBON KOSONG', 'KEMAYORAN', 'SERDANG', 'SUMUR BATU', 'UTAN PANJANG'],
      'MENTENG': ['CIKINI', 'GONDANGDIA', 'KEBON SIRIH', 'MENTENG', 'PEGANGSAAN'],
      'SAWAH BESAR': ['GUNUNG SAHARI UTARA', 'KARANG ANYAR', 'KARTINI', 'MANGGA DUA SELATAN', 'PASAR BARU'],
      'SENEN': ['BUNGUR', 'KENARI', 'KRAMAT', 'KWITANG', 'PASEBAN', 'SENEN'],
      'TANAH ABANG': ['BENDUNGAN HILIR', 'GELORA', 'KAMPUNG BALI', 'KARET TENGSIN', 'KEBON KACANG', 'KEBON MELATI', 'PETAMBURAN']
    },
    'KOTA ADM. JAKARTA SELATAN': {
      'CILANDAK': ['CILANDAK BARAT', 'CIPETE SELATAN', 'GANDARIA SELATAN', 'LEBAK BULUS', 'PONDOK LABU'],
      'JAGAKARSA': ['CIGANJUR', 'CIPEDAK', 'JAGAKARSA', 'LENTENG AGUNG', 'SRENGSENG SAWAH', 'TANJUNG BARAT'],
      'KEBAYORAN BARU': ['CIPETE UTARA', 'GANDARIA UTARA', 'GUNUNG', 'KRAMAT PELA', 'MELAWAI', 'PETOGOGAN', 'PULO', 'RAWA BARAT', 'SELONG', 'SENAYAN'],
      'KEBAYORAN LAMA': ['CIPULIR', 'GROGOL SELATAN', 'GROGOL UTARA', 'KEBAYORAN LAMA SELATAN', 'KEBAYORAN LAMA UTARA', 'PONDOK PINANG'],
      'MAMPANG PRAPATAN': ['BANGKA', 'KUNINGAN BARAT', 'MAMPANG PRAPATAN', 'PELA MAMPANG', 'TEGAL PARANG'],
      'PANCORAN': ['CIKOKO', 'DUREN TIGA', 'KALIBATA', 'PANCORAN', 'PENGADEGAN', 'RAWAJATI'],
      'PASAR MINGGU': ['CILANDAK TIMUR', 'JATI PADANG', 'KEBAGUSAN', 'PASAR MINGGU', 'PEJATEN BARAT', 'PEJATEN TIMUR', 'RAGUNAN'],
      'PESANGGRAHAN': ['BINTARO', 'PESANGGRAHAN', 'PETUKANGAN SELATAN', 'PETUKANGAN UTARA', 'ULUJAMI'],
      'SETIA BUDI': ['GUNTUR', 'KARET', 'KARET KUNINGAN', 'KARET SEMANGGI', 'KUNINGAN TIMUR', 'MENTENG ATAS', 'PASAR MANGGIS', 'SETIABUDI'],
      'TEBET': ['BUKIT DURI', 'KEBON BARU', 'MANGGARAI', 'MANGGARAI SELATAN', 'MENTENG DALAM', 'TEBET BARAT', 'TEBET TIMUR']
    },
    'KOTA ADM. JAKARTA TIMUR': {
      'CAKUNG': ['CAKUNG BARAT', 'CAKUNG TIMUR', 'JATINEGARA', 'PENGGILINGAN', 'PULO GEBANG', 'RAWA TERATE', 'UJUNG MENTENG'],
      'CIPAYUNG': ['BAMBU APUS', 'CEGER', 'CILANGKAP', 'CIPAYUNG', 'LUBANG BUAYA', 'MUNJUL', 'PONDOK RANGGON', 'SETU'],
      'CIRACAS': ['CIBUBUR', 'CIRACAS', 'KELAPA DUA WETAN', 'RAMBUTAN', 'SUSUKAN'],
      'DUREN SAWIT': ['DUREN SAWIT', 'KLENDER', 'MALAKA JAYA', 'MALAKA SARI', 'PONDOK BAMBU', 'PONDOK KELAPA', 'PONDOK KOPI'],
      'JATINEGARA': ['BALI MESTER', 'BIDARA CINA', 'CIPINANG BESAR SELATAN', 'CIPINANG BESAR UTARA', 'CIPINANG CEMPEDAK', 'CIPINANG MUARA', 'KAMPUNG MELAYU', 'RAWA BUNGA'],
      'KRAMAT JATI': ['BALEKAMBANG', 'BATU AMPAR', 'CAWANG', 'CILILITAN', 'DUKUH', 'KRAMAT JATI', 'TENGAH'],
      'MAKASAR': ['CIPINANG MELAYU', 'HALIM PERDANA KUSUMA', 'KEBON PALA', 'MAKASAR', 'PINANG RANTI'],
      'MATRAMAN': ['KAYU MANIS', 'KEBON MANGGIS', 'PAL MERIAM', 'PISANGAN BARU', 'UTAN KAYU SELATAN', 'UTAN KAYU UTARA'],
      'PASAR REBO': ['BARU', 'CIJANTUNG', 'GEDONG', 'KALISARI', 'PEKAYON'],
      'PULO GADUNG': ['CIPINANG', 'JATI', 'KAYU PUTIH', 'PISANGAN TIMUR', 'PULO GADUNG', 'RAWAMANGUN']
    },
    'KOTA ADM. JAKARTA UTARA': {
      'CILINCING': ['CILINCING', 'KALI BARU', 'MARUNDA', 'ROROTAN', 'SEMPER BARAT', 'SEMPER TIMUR', 'SUKAPURA'],
      'KELAPA GADING': ['KELAPA GADING BARAT', 'KELAPA GADING TIMUR', 'PEGANGSAAN DUA'],
      'KOJA': ['KOJA', 'LAGOA', 'RAWA BADAK SELATAN', 'RAWA BADAK UTARA', 'TUGU SELATAN', 'TUGU UTARA'],
      'PADEMANGAN': ['ANCOL', 'PADEMANGAN BARAT', 'PADEMANGAN TIMUR'],
      'PENJARINGAN': ['KAMAL MUARA', 'KAPUK MUARA', 'PEJAGALAN', 'PENJARINGAN'],
      'TANJUNG PRIOK': ['KEBON BAWANG', 'PAPANGGO', 'SUNGAI BAMBU', 'SUNTER AGUNG', 'SUNTER JAYA', 'TANJUNG PRIOK', 'WARAKAS']
    }
  },

  /* ====================================================================
     BALI — 9 Kabupaten/Kota (kecamatan lengkap)
     ==================================================================== */
  'BALI': {
    'KOTA DENPASAR': {
      'DENPASAR BARAT': ['DAUH PURI', 'DAUH PURI KANGIN', 'DAUH PURI KAUH', 'DAUH PURI KLOD', 'PADANGSAMBIAN', 'PADANGSAMBIAN KAJA', 'PADANGSAMBIAN KLOD', 'PEMECUTAN', 'PEMECUTAN KLOD', 'TEGAL HARUM', 'TEGAL KERTHA'],
      'DENPASAR SELATAN': ['PANJER', 'PEDUNGAN', 'PEMOGAN', 'RENON', 'SANUR', 'SANUR KAJA', 'SANUR KAUH', 'SESETAN', 'SIDAKARYA'],
      'DENPASAR TIMUR': ['DANGIN PURI', 'DANGIN PURI KANGIN', 'DANGIN PURI KAUH', 'DANGIN PURI KLOD', 'KESIMAN', 'KESIMAN KERTALANGU', 'KESIMAN PETILAN', 'PENATIH', 'PENATIH DANGIN PURI', 'SUMERTA', 'SUMERTA KAJA', 'SUMERTA KAUH', 'SUMERTA KLOD'],
      'DENPASAR UTARA': ['DANGIN PURI KAJA', 'DAUH PURI KAJA', 'PEGUYANGAN', 'PEGUYANGAN KAJA', 'PEGUYANGAN KANGIN', 'PEMECUTAN KAJA', 'TONJA', 'UBUNG', 'UBUNG KAJA']
    },
    'KAB. BADUNG': {
      'ABIANSEMAL': ['ABIANSEMAL', 'ABIANSEMAL DAUH YEH CANI', 'AYUNAN', 'BLAHKIUH', 'BONGKASA', 'BONGKASA PERTIWI', 'DARMASABA', 'JAGAPATI', 'MAMBAL', 'MEKAR BHUANA', 'PUNGGUL', 'SEDANG', 'SELAT', 'SIBANG GEDE', 'SIBANG KAJA', 'TAMAN', 'ANGANTAKA'],
      'KUTA': ['KEDONGANAN', 'KUTA', 'LEGIAN', 'SEMINYAK', 'TUBAN'],
      'KUTA SELATAN': ['BENOA', 'JIMBARAN', 'PECATU', 'TANJUNG BENOA', 'UNGASAN'],
      'KUTA UTARA': ['CANGGU', 'DALUNG', 'KEROBOKAN', 'KEROBOKAN KAJA', 'KEROBOKAN KLOD', 'TIBUBENENG'],
      'MENGWI': ['BUDUK', 'CEMAGI', 'GULINGAN', 'KAPAL', 'KEKERAN', 'KUWUM', 'LUKLUK', 'MENGWI', 'MENGWITANI', 'MUNGGU', 'PENARUNGAN', 'SADING', 'SEMPIDI', 'SOBANGAN', 'TUMBAK BAYUH', 'WERDI BHUWANA'],
      'PETANG': ['BELOK', 'CARANGSARI', 'GETASAN', 'PANGSAN', 'PELAGA', 'PETANG', 'SULANGAI']
    },
    'KAB. BANGLI': ['BANGLI', 'KINTAMANI', 'SUSUT', 'TEMBUKU'],
    'KAB. BULELENG': ['BANJAR', 'BULELENG', 'BUSUNGBIU', 'GEROKGAK', 'KUBUTAMBAHAN', 'SAWAN', 'SERIRIT', 'SUKASADA', 'TEJAKULA'],
    'KAB. GIANYAR': ['BLAHBATUH', 'GIANYAR', 'PAYANGAN', 'SUKAWATI', 'TAMPAKSIRING', 'TEGALLALANG', 'UBUD'],
    'KAB. JEMBRANA': ['JEMBRANA', 'MELAYA', 'MENDOYO', 'NEGARA', 'PEKUTATAN'],
    'KAB. KARANGASEM': ['ABANG', 'BEBANDEM', 'KARANGASEM', 'KUBU', 'MANGGIS', 'RENDANG', 'SELAT', 'SIDEMEN'],
    'KAB. KLUNGKUNG': ['BANJARANGKAN', 'DAWAN', 'KLUNGKUNG', 'NUSA PENIDA'],
    'KAB. TABANAN': ['BATURITI', 'KEDIRI', 'KERAMBITAN', 'MARGA', 'PENEBEL', 'PUPUAN', 'SELEMADEG', 'SELEMADEG BARAT', 'SELEMADEG TIMUR', 'TABANAN']
  }

};

/* ======================================================================
   Accessor Helpers
   ====================================================================== */

/** Daftar Provinsi (urut alfabetis). */
function getProvinsiList() {
  return Object.keys(WILAYAH_INDONESIA).sort();
}

/** Daftar Kabupaten/Kota pada satu Provinsi. */
function getKabupatenList(provinsi) {
  const prov = WILAYAH_INDONESIA[provinsi];
  if (!prov) return [];
  return Object.keys(prov).sort();
}

/** Daftar Kecamatan pada satu Kabupaten/Kota. */
function getKecamatanList(provinsi, kabupaten) {
  const prov = WILAYAH_INDONESIA[provinsi];
  if (!prov) return [];
  const kab = prov[kabupaten];
  if (!kab) return [];
  return (Array.isArray(kab) ? kab.slice() : Object.keys(kab)).sort();
}

/**
 * Daftar Kelurahan/Desa pada satu Kecamatan.
 * Jika kecamatan belum memiliki data kelurahan (nilai kabupaten berupa array),
 * dipakai fallback berisi nama kecamatan itu sendiri agar dropdown tetap
 * dapat dipilih pada prototipe.
 */
function getKelurahanList(provinsi, kabupaten, kecamatan) {
  const prov = WILAYAH_INDONESIA[provinsi];
  if (!prov) return [];
  const kab = prov[kabupaten];
  if (!kab) return [];
  if (Array.isArray(kab)) {
    return kab.includes(kecamatan) ? [kecamatan] : [];
  }
  const kel = kab[kecamatan];
  if (!kel || kel.length === 0) return kecamatan ? [kecamatan] : [];
  return kel.slice().sort();
}
